### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by HERITAGEALABI** [bancodobrasil/stop-analyzing-embed#107]
I'm Heritage
I want a task to be assigned to me

**Comment by tiagostutz** [comment]
Hi @HERITAGEALABI !! 👋🏻 Welcome to stop analyzing!
I'm sure we will be building a great project together here.

Do you want to tackle this one https://github.com/bancodobrasil/stop-analyzing-embed/issues/95
If so, please go to this issue, comment there and I'll assign it to you right away!

**Comment by jvrenes** [comment]
Hi, I just ended one course about Front-End with React and React Native, and I'd like to collaborate on my first opensource project.
Thanks!

**Comment by tiagostutz** [comment]
Hi @jvrenes 👋🏻 ! Welcome to stop analyzing...!! 
I'm sure you will bring valuable contributions to the project. If you want to start, there are two issues that are a good starting point you could go: https://github.com/bancodobrasil/stop-analyzing-embed/issues/55 and https://github.com/bancodobrasil/stop-analyzing-embed/issues/95

You can choose one of those issues, read the [CONTRIBUTING guidelines](https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/CONTRIBUTING.md), fork the project and submit your PR. If you need any assistance during the process, please feel free to ask on the issue for any help.

So, if you think that's a good starting point, please comment on the issue you want to tackle and I'll assign to you right away!
🚀

**Comment by aditya28sarin** [comment]
Hi, I have worked with HTML, CSS and Bootstrap, can you assign me something related to that?

**Comment by tiagostutz** [comment]
Hi @aditya28sarin !! 👋🏻  
First of all, welcome to Stop Analyzing and thanks for offering help.!

Sure, we have this issue #56 that you could take a look. It was being addressed by https://github.com/bancodobrasil/stop-analyzing-embed/pull/104 but it got stuck, so feel free to tackle that. 

If you want to grab this one, please comment on the #56 so I can assign that issue to you asap.

If you need any further assistance, please let me know.
