### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by therealsylaucoin** [bancodobrasil/stop-analyzing-embed#110]
Hi! I'm Syl. 
A recent Front End Web Dev graduate. 
I'm always looking for new ways to learn, and I'd love to work on an issue :)
Thanks!

**Comment by therealsylaucoin** [comment]
Hi @tiagostutz - Thank you! I'd love to give it a shot. Please go ahead and assign it to me. :)

**Comment by tiagostutz** [comment]
Awesome! 
Please, post a comment on #94 so I can assign it to you. Its not possible to assign the issue to users that haven't interact with the issue yet.
I'll assign it to you right away.!

**Comment by Shubham-Vishwakarma** [comment]
This is also not an issue
@tiagostutz Please close this
Closing these things will help new beginners in much better way
