### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by shoaibkamalkhan** [bancodobrasil/stop-analyzing-embed#112]
Hi my name is Shoaib Kamal Khan and I am a recent Front End Web Development Techdegree graduate from Treehouse. I would love to contribute to any open issues you have as a first timer. Please let me know if you have any issues that I can work on. I am proficient in the following:

HTML, CSS, JavaScript
Mobile-First Responsive Web Design
Flexbox
Grid Layout
jQuery
Ajax
Fetch API
JSON
Sass
Media Element.js
Bootstrap
SEO(Search Engine Optimization)
Semantic HTML
Front End Optimization
Git
Wireframing and Prototyping
Adobe XD
Sketch
Figma
Graphic Design
Adobe Illustrator
Adobe Photoshop(PSD to HTML)

Here is the link to my portfolio:

https://shoaibkamalkhan.github.io/

**Comment by tiagostutz** [comment]
Hi @shoaibkamalkhan !
Welcome to Stop Analyzing.! 👋🏻  
Sorry for the late response.

Would you like to tackle https://github.com/bancodobrasil/stop-analyzing-embed/issues/72 ? If so, please comment on the issue and I'll assign it to you right away.

If this is not suitable for you we can work on another task, ok?

Thanks a lot for offering help!

**Comment by shoaibkamalkhan** [comment]
Hi @tiagostutz! Thanks a lot for the welcome and the reply! I have commented on #72. Can you please assign it to me. Thank you for your response!😀👍🏻🙏🏻🎶

**Comment by Shubham-Vishwakarma** [comment]
This not an issue
@tiagostutz Please close this
