### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by RidamGarg** [bancodobrasil/stop-analyzing-embed#113]
Hi! I am pursuing my Bachelor's degree in Software Engineering and am looking for a project to contribute to so that I can learn new things and improve my skills.

My education mainly focused on full-stack web development. I also know Java and C++.

**Comment by tiagostutz** [comment]
HI there @RidamGarg 👋🏻 ! Welcome to Stop Analyzing.
First of all, thanks for offering help.

Stop Analyzing is composed by two repos: frontend and backend. This repo here is focused on Frontend development and [this other repohttps://github.com/bancodobrasil/stop-analyzing-api) is focused on the Backend development part. Which one would you like to make your contribution?

**Comment by RidamGarg** [comment]
I would like to contribute to Frontend development. As in the second repo, the code is in 'go' and I have used nodejs in backend development.

**Comment by RidamGarg** [comment]
Sir,Please Response

**Comment by tiagostutz** [comment]
Hi there @RidamGarg ! Sorry for the late response.

How about the issue #118 ? Would you like to try it out?

**Comment by RidamGarg** [comment]
Yes, I want to solve this issue

**Comment by RidamGarg** [comment]
Sir, Sorry to say that my college exams have started so, I am unable to work on this. Please assign this issue to anyone else.
I will definitely solve more and more issues after my exams get over.
Thank You.
