### ISSUE TITLE
I want to contribute 

### ISSUE THREAD

**Issue by TD-17** [bancodobrasil/stop-analyzing-embed#115]
Hello ! I am Tanya and m currently pursuing my bachelor's in computer science and engineering. I want to contribute in new projects related to frontend development to improve my skills.

**Comment by tiagostutz** [comment]
Hi there @TD-17 ! 👋🏻 
Welcome to Stop Analyzing. Nice to have you on board!

What do you think about tackling https://github.com/bancodobrasil/stop-analyzing-embed/issues/94 ?

**Comment by TD-17** [comment]
> Hi there @TD-17 ! 👋🏻
> Welcome to Stop Analyzing. Nice to have you on board!
> 
> What do you think about tackling #94 ?

Yeah I would like to tackle this issue ! Will you assign me this ?

**Comment by tiagostutz** [comment]
Sure, you just need comment on the #94 for me to be able to assign it to you and I'm doing this right away.!
