### ISSUE TITLE
Upgrade Tailwind to 2.0.0

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#118]
At the end of 2020 Tailwind v2 has been released and I think we should go for it to be just in time with the styling and tooling improvements it has introduced.

**Comment by RidamGarg** [comment]
Yes,I want to solve this issue

**Comment by tiagostutz** [comment]
Nice!
I have just assigned the issue to you. 

If you need any assistance, please comment here.

**Comment by RidamGarg** [comment]
Sir, Sorry to say that my college exams have started so, I am unable to work on this. Please assign this issue to anyone else.
I will definitely solve more and more issues after my exams get over.
Thank You.

**Comment by adam-p-git** [comment]
Hi! 
I'd like to take on this issue.

**Comment by tiagostutz** [comment]
> Sir, Sorry to say that my college exams have started so, I am unable to work on this. Please assign this issue to anyone else.
> I will definitely solve more and more issues after my exams get over.
> Thank You.

Nice, @RidamGarg ! Thanks for releasing the issue.
When you are ready to tackle more issues, we are here waiting for you.

Good luck on your exams! =)

**Comment by tiagostutz** [comment]
> Hi!
> I'd like to take on this issue.

Hi @adam-p-git ! 👋🏻 
Welcome to stop analyzing.! Thanks for offering help.

I have just assigned the issue to you. If you need any assistance, please comment here.
