### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by PedroEnciso** [bancodobrasil/stop-analyzing-embed#120]
Hi! I'd like to contribute to the front-end of this project. Are there any issues I can help with?

**Comment by tiagostutz** [comment]
Hi @PedroEnciso ! 👋🏻
Welcome to Stop Analyzing. Thanks for offering help! =)

Would do you think about tackling one of #95 or #94?

**Comment by tiagostutz** [comment]
Hi @N-coder-bot !
Would you be interested in checking the https://github.com/bancodobrasil/stop-analyzing-embed/issues/72 out?

**Comment by deepaahuja92** [comment]
Hello! I am Deepa Ahuja and I like frontend development.I know  HTML,,CSS AND JAVASCRIPT and basics of Reactjs.I want to contribute in the issues please can you assign me some issues.

**Comment by tiagostutz** [comment]
Hi there @deepaahuja92  ! 👋🏻 
Welcome to stop analyzing.!

First of all sorry sorry for the laaaaate response.

Let's get something for you to tackle. Have you read the README instructions? Were you able to bring the project up and running? Need some help with that?
Please let me know as soon as you put the project running locally and then let's tackle some issues. Ok?
