### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by Dythic** [bancodobrasil/stop-analyzing-embed#123]
Hello, I saw your project and I want to contribute. I have technical skills in Front and Back but I have never contributed to a project

**Comment by tiagostutz** [comment]
Hi @Dythic 👋🏻 ! Welcome to Stop Analyzing.!
Thanks for offering help.

Would do you think about tackling one of #72 or #95?

**Comment by Dythic** [comment]
Thank you, I think I start with #95

**Comment by Dythic** [comment]
Hello, I am working on the problem, but I am afraid of going in the wrong direction. From what I understood the goal is to improve the API so that it returns plants randomly ?

**Comment by tiagostutz** [comment]
Hi there @Dythic !! Sorry for the late response... to be fare I didn't receive this notification.
Yes, you are correct about the main goal. BTW, thanks for you PR, let's discuss the details there, but as I could see that was a great PR! 😉
