### ISSUE TITLE
I want to Contribute

### ISSUE THREAD

**Issue by MDPuneethReddy** [bancodobrasil/stop-analyzing-embed#124]

**Comment by MDPuneethReddy** [comment]
Hello I am puneeth, I would Like to contibute it would be my first contribution

**Comment by tiagostutz** [comment]
Hi @MDPuneethReddy  👋🏻 ! Welcome to Stop Analyzing.!
Thanks for offering help.

Would do you think about tackling one of #72?

**Comment by Mellowan** [comment]
Hello I'm mellowan and I would love to contribute, I'm a first timer

**Comment by tiagostutz** [comment]
Hi @Mellowan  👋🏻 ! Welcome to Stop Analyzing.!

Would do you think about tackling #72?

**Comment by MDPuneethReddy** [comment]
Hi , Can I know what we have to do in branch #72 ?
