### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by sapgit97** [bancodobrasil/stop-analyzing-embed#129]
Hi I am new to open source. I would like to start contributing. It would be great if you could find  task for me.

**Comment by tiagostutz** [comment]
Hi @sapgit97 !
What about tackling https://github.com/bancodobrasil/stop-analyzing-embed/issues/95? Want to give it a try?

**Comment by sapgit97** [comment]
Hi, from what I understood going through the linked issues, it would be something like this:

`router.get("/choice", (req, res) => {
  // retrieving query parameters
  const queries = req.query;
  const previousChoices = queries && queries.previous;
  const count = (queries && queries.count) || 2;

  // calculating matched choices
  const matchedChoices = getMatchedChoices(previousChoices, count);

  // return matched choices
  const response = {
    choices: matchedChoices
  }
  res.json(response);
});

// logic to get matched choices
// placeholder only currently
function getMatchedChoices(previousChoices, count) {
  // TODO: implement this function to return matched choices based on previous ones.
  const dbChoices = (db && db.choices) || [];
  const dbChoicesLength = dbChoices.length || 0;
  let returnCount = (dbChoicesLength > count)? count : dbChoicesLength;
  const result = dbChoices.slice(0, returnCount);
  return result;
}`

and also I would need to add few more choices to the db file. Should I also have to implement the getMatchedChoices function? If yes, what should be the logic behind that?

**Comment by sapgit97** [comment]
Hi @tiagostutz any comments?

**Comment by tiagostutz** [comment]
Hi @sapgit97! Sorry for the late response...

> Should I throw some error if any of the previous queryParameters does not match any id in choices array of db
You could return a 400 (Bad Request)

> Should I also have to implement the getMatchedChoices function? If yes, what should be the logic behind that?
Nope, this is just a mock function, don't need any logic. You can randomly return the result. The actual API is being built here: https://github.com/bancodobrasil/stop-analyzing-api. BTW, if you are interested in contributing on a Golang project, you could tackle some issues there.

**Comment by sapgit97** [comment]
Hi @tiagostutz, added PR #130.

**Comment by AkshithaReddy1899** [comment]
Hi. this is Akshitha, a newbie. I am comfortable working with HTML, CSS, and javascript. is there any issue that I can solve or help with?

**Comment by tiagostutz** [comment]
Hi there @AkshithaReddy1899   ! 👋🏻 
Welcome to stop analyzing.!

First of all sorry sorry for the laaaaate response

Let's get something for you to tackle. Have you read the README instructions? Were you able to bring the project up and running? Need some help with that?
Please let me know as soon as you put the project running locally and then let's tackle some issues. Ok?
