### ISSUE TITLE
Review, fix and complement TimerComponent.test, useTimerComponentModel.test and Card.test

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#13]
All of the tests are using [testing-library](https://testing-library.com).

In the Card testes, check why they are failing: the test is outdated or the component has issues.

In TimerComponent and useTimerComponentModel, create tests to help develop them and guarantee that different scenarios don't break the component and, if wrong parameters are passed, the component should notice that and return the properly error instructions.

**Comment by bearcub3** [comment]
@tiagostutz assign to me, please! 😁

**Comment by eduardomrodrigues** [comment]
@tiagostutz, can I change div to img tag? 
I think it's better for semantic reasons

**Comment by tiagostutz** [comment]
Good point, @eduardomrodrigues !
I opened the issue #15 to discuss this question. I think that's a good idea. What do you think?

**Comment by bearcub3** [comment]
@eduardomrodrigues  I am open for the discussion! I'd like to hear what you think. 😃

**Comment by eduardomrodrigues** [comment]
Hi, @bearcub3! Nice to meet you! Thank's for this opportunity! Let's take this discussion on #15 ?

**Comment by bearcub3** [comment]
Hello 👋 @eduardomrodrigues, yes go ahead!

**Comment by bearcub3** [comment]
Hello 👋  @tiagostutz, I won't be able to participate for a while. I have just started building an app and it has limited time to complete it for the submission. I will try to complete the test based on your review asap and then close this issue.

**Comment by tiagostutz** [comment]
Hi there @bearcub3 !! ❤️ 

First of all, thanks for all your contributions. You've been such a great community member. I hope you are enjoying the experience as much as we are enjoying to have you here.

About the issue, don't worry. If you could finish it, it would be great, but if it is not possible, that's not a problem at all. We can assign it to someone.

I hope you could come back asap and if you want to keep an eye here just to bring your opinions and suggestions, that would be very valuable also. 

I hope the best on this App development you are working on! 🤓

**Comment by finhaa** [comment]
Hi @tiagostutz! Can I get this issue for complete?

**Comment by tiagostutz** [comment]
Sure, go on!

Thanks for your help on that, @finhaa !
