### ISSUE TITLE
I want to contribute.

### ISSUE THREAD

**Issue by shivam-0510** [bancodobrasil/stop-analyzing-embed#134]
Hi I am Shivam Gupta, I am new to open source. I would like to start contributing. It would be great if you could find task for me.

**Comment by tiagostutz** [comment]
Hi there @shivam-0510  ! 👋🏻 
Welcome to stop analyzing.!

First of all sorry sorry for the laaaaate response

Let's get something for you to tackle. Have you read the README instructions? Were you able to bring the project up and running? Need some help with that?
Please let me know as soon as you put the project running locally and then let's tackle some issues. Ok?

**Comment by shivam-0510** [comment]
Yes,Ok

**Comment by govind2404** [comment]
Hey! I am Govind I am beginner at open source and I want to contribute to this project. Please help me to get started.

**Comment by Abhishek332** [comment]
Hey ! I am Abhishek. I am new to Open Source and want to start contributing, not know how to get into it. Please help me to get started.
