### ISSUE TITLE
Add eslint and prettier workflows

### ISSUE THREAD

**Issue by JapneetSingh5** [bancodobrasil/stop-analyzing-embed#17]
I think adding a linter and prettier would be fruitful in the long run as the codebase grows. It will also help keep the code uniform for all the contributors and maybe even introduce first-timers to these concepts.
We can add Github Actions workflows as well.

**Comment by bearcub3** [comment]
I thought of that, too. that's a good idea!

**Comment by tiagostutz** [comment]
Sounds great! 
@JapneetSingh5 do you want to grap this one and pass the #16 to another person or do you want to pass this one here to someone else?

**Comment by JapneetSingh5** [comment]
Yeah sure, no problem!

**Comment by eduardomrodrigues** [comment]
Very good ideia, @JapneetSingh5! I'm on it! Thanks for this opportunity!

**Comment by tiagostutz** [comment]
Awesome!

The issue is yours, @eduardomrodrigues .! 

Tell me if you need any special access on the repo to make this configurations.

@JapneetSingh5 would you like to point any particular projects as references?

**Comment by JapneetSingh5** [comment]
I follow this gist myself, I generally use the airbnb style guide. 

https://gist.github.com/bradtraversy/aab26d1e8983d9f8d79be1a9ca894ab4

**Comment by eduardomrodrigues** [comment]
The project has this [eslint-config-react-app](https://www.npmjs.com/package/eslint-config-react-app), I learn about it and, for me,  it's sufficient, can be configurable and we don't have to eject the project.
This [Prettier and Style guided](https://gist.github.com/bradtraversy/aab26d1e8983d9f8d79be1a9ca894ab4) are awesome.
I'll put this all together and make a proposition for you
