### ISSUE TITLE
I would like to contribute. =)

### ISSUE THREAD

**Issue by lucasravy** [bancodobrasil/stop-analyzing-embed#18]
Hey there! :grin: 

I would like to contribute to this project. Is there anything I can help with?
I can do some stuffs with HTML, CSS and JavaScript. I think I can manage somethings with Typescript as well, although I don't have much experience. 

Looking forward to contribute. :smiley:

**Comment by tiagostutz** [comment]
Hi @lucasravy ! Welcome on board..!

I got this..! I'm working on a issue for you and will link it back here asap.

Cheers! 🥂

**Comment by tiagostutz** [comment]
I was thinking about opening an issue regarding to Dockerizing the project. Would you like to take that to begin?

**Comment by lucasravy** [comment]
@tiagostutz that would be great! Count me in! :nerd_face:

**Comment by tiagostutz** [comment]
Awesome.! 
I've just created the issue #19 . If are able to grab that, please reply me [there](https://github.com/bancodobrasil/stop-analyzing-embed/issues/19) so I can assign it to you. 🏃

**Comment by tiagostutz** [comment]
@lucasravy I've just assigned #19 to @giteshk11, ok?

I'm working on a new issue for you right away. 👟

**Comment by lucasravy** [comment]
@tiagostutz Thats ok. Still waiting 😁

**Comment by tiagostutz** [comment]
@lucasravy how about #19 ? It is still available... By the way I think this issue can become a interesting open source experience. Take a look at this comment: https://github.com/bancodobrasil/stop-analyzing-embed/issues/19#issuecomment-652023800

**Comment by tiagostutz** [comment]
If you want to grap that, please comment on the issue.

**Comment by lucasravy** [comment]
@tiagostutz, I would like to try to solve this issue. :grin:

**Comment by tiagostutz** [comment]
Assigned my friend!
