### ISSUE TITLE
Create a Git Hook with Prittier and ESLint

### ISSUE THREAD

**Issue by eduardomrodrigues** [bancodobrasil/stop-analyzing-embed#22]
Before commit, make the prittier and ESLint run in the code and abort when ESLint show error

**Comment by tiagostutz** [comment]
That will be awesome!

@JapneetSingh5  want to take this one?

**Comment by JapneetSingh5** [comment]
Sure, this refers to Github Actions workflow right @eduardomrodrigues ?

**Comment by eduardomrodrigues** [comment]
@JapneetSingh5, I started to read about it and I found this: [husky](https://www.npmjs.com/package/husky)
Now I started to avaliate this solution, the entire control of hook is in client machine, maybe it's a problem, but is very easy to configure, my test ran in 10 minutes of coding.
I don't understand Github Actions yet, I'll have to learn about it, but I really wanna, because the CI/CD lifecycle can be configured on it(right?) and I really want to know how to do that!

What do you think?

Thank you again!

**Comment by JapneetSingh5** [comment]
If you want to work on this issue and you have already done some great research, go ahead and do it 👍🏻👍🏻. I will be happy to collaborate if you feel stuck anywhere ☺️☺️

**Comment by JapneetSingh5** [comment]
You can configure a basic workflow from the actions tab I think. Github's official documentation is also pretty nifty to learn about actions.

**Comment by eduardomrodrigues** [comment]
Alright! I'm on it! Thank you!

**Comment by eduardomrodrigues** [comment]
DevTeam, after my studies I have this conclusion: the husky is the best solution to this phase of our project
This is my report:
- The Github actions are normally used for entire CI/CD cycle, the Lint and tests are tasks for this; 
- [Husky](https://www.npmjs.com/package/husky) works in pre-commit and pre-push phase, ideal for using prittier

Husky was successful deployed and generate this:
https://github.com/bancodobrasil/stop-analyzing-embed/pull/24

What do you think?

Thank you
