### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by eduardomrodrigues** [bancodobrasil/stop-analyzing-embed#29]
Hi, devteam!

I can contribute with developer some react components!

Thank you!

**Comment by tiagostutz** [comment]
Hi @eduardomrodrigues ! Thanks for your valuable contributions!

I'll create another issue for you asap.  Meanwhile, if you could, please take a look at #30. Maybe you could give some help there.

**Comment by eduardomrodrigues** [comment]
Hi, @tiagostutz! Off course, will be my pleasure!
