### ISSUE TITLE
Project infrastructure and design patterns 

### ISSUE THREAD

**Issue by rafamarts** [bancodobrasil/stop-analyzing-embed#3]
Hi everyone,

I've created this issue for discussion about design patterns to be used in this project. I was checking the repository and saw that the project (package.js) is not in root directory, should it be like this?
Also, I think that we should define test coverage and add those information in CONTRIBUTING.md file. Each new TS file should have a test file located in a test directory in root directory, following the same directory structure of project. For example, all components that is in directory app>src>components should have a respective test file in test>app>src>components.

What do you think and what you suggests about that?

**Comment by tiagostutz** [comment]
Hi @rafamarts! Thanks for contributing to Stop Analyzing!

About your suggestions:

> saw that the project (package.js) is not in root directory, should it be like this?

Yes. We will soon have a Dockerfile and docker-compose.yml files here for running the project locally and it is better to not mix those files with the actual code of the solution. So, we keep the source code in the app folder and all of other "accessories" stuff we keep outside.

> Also, I think that we should define test coverage and add those information in CONTRIBUTING.md file. Each new TS file should have a test file located in a test directory in root directory, following the same directory structure of project. For example, all components that is in directory app>src>components should have a respective test file in test>app>src>components.

That's a great suggestion. I think we could start a CONTRIBUTING.md file with general guidelines and practices and when we have enough examples of testing patterns and code coverage we put those instructions there. We are following the "spec by example" approach istead of the "example by spec", so let's keep those guidelines you provided but we will strict to them when we have enough examples. Sounds good?


So,  would you like to make your first code contribution? If so, do you prefer to work on writing the CONTRIBUTING.md file, coding HTML/JS/CSS? Building the docker getting started stuff? Tell me a bit more about how would you like to contribute and I'll open one or more issues for you to choose one.

**Comment by rafamarts** [comment]
I would like to make my contribution coding. And then, when we have enough examples, I can contribute with CONTRIBUTING.md file if still need. Thank you!

**Comment by tiagostutz** [comment]
Nice. 
I have invited you to be a collaborator of the project I've written the issue #4  to you. As soon as you accept the invite, I'm assigining the issue to you.
