### ISSUE TITLE
Create a "Pinterest like" Card style using a theming approach

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#30]
Create a theming structure for the application implementing as the first use case Pinterest style card, like this https://business.pinterest.com/advertise/#ad-formats

<img width="400" alt="Captura de Tela 2020-07-08 às 19 31 04" src="https://user-images.githubusercontent.com/3986989/86976841-bf0c7d80-c151-11ea-97a8-2d054bb48ab7.png">

@giteshk11 @JapneetSingh5 I'll get some references to paste here on how to create a theme structure. 
If someone has references, please share it here to enrich the discussion here.

**Comment by tiagostutz** [comment]
Some references:
- http://www.csszengarden.com/: this is old, from my early CSS days, but is a good inspiration on how it is possible to themefy a content using pure vanilla CSS
- https://blog.logrocket.com/how-to-create-better-themes-with-css-variables-5a3744105c74/ : some directions on CSS variable, which is somethig really useful for this work on themes
- https://codepen.io/michellebarker/pen/zbKZyp : simple example on override variables to themify

Who want's to take that?

**Comment by finhaa** [comment]
Hey @tiagostutz 

There is somebody working in this issue? I would be happy to help here, but I didn't quite understand how to work on it.

**Comment by tiagostutz** [comment]
Hi @finhaa !! I just answeared you in another issue and now noticed you have asked for this issue here... ehehehehe...
Well, could you take a look at that one first and them come back to this (if it is still available)? I mean, the issue #13 is getting old and I think we should close that, so if you could help us on that it would be really helpful.!

What do you think?

**Comment by finhaa** [comment]
Yeah hahahah i just saw the issue #13 and was analyzing the discussion in the PR #14. Im going to comment in the other issue I created for accept  what was proposed.

**Comment by JapneetSingh5** [comment]
Hi! Thankyou for this. I'll look into it and hopefully open a PR before weekend!

**Comment by tiagostutz** [comment]
Awesome, @JapneetSingh5 ! 

Just assigned that to you.

**Comment by tiagostutz** [comment]
Hi @JapneetSingh5 ! 👋🏻 

There's a new contributor asking for an issue and I'd like to know whether you have already started this issue or if we could asssign it to this new contributor, in #35.

**Comment by JapneetSingh5** [comment]
Hey @tiagostutz! 
Sorry for the delay, I was a little busy with some work. 
I haven't worked a lot on this so I have no problems if the new contributor wants to work on this one. I will look out for more tasks in the future!

**Comment by tiagostutz** [comment]
Not a problem at all @JapneetSingh5 !
I'm asking you because as you are part of the team now I thought you would understand and be welcoming to this, like you are. 😄 

Thanks for that and if you would like to open new issues or help others on issues and PRs you are welcome!

**Comment by divyaYK** [comment]
Hey @tiagostutz! 
I'd like to take up this issue, thanks! 😊

**Comment by tiagostutz** [comment]
Hi @divyaYK !

Awsome. Its yours =)

If you have any doubt, please bring it to the table.

Happy coding! =)
