### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by reedhop24** [bancodobrasil/stop-analyzing-embed#32]
Hello!

I would love to contribute in any way I can! (Be gentle this is my first time opening an issue)

Thanks,

**Comment by tiagostutz** [comment]
Hi @reedhop24 ! 👋 
I really hope you are doing well..! 

First of all, t**hank you so much for offering your help**. It will be really nice to have you on board. 🚀 

As I'm going to create an issue specially to you, I'd like to know a bit more about what are the technologies or skills you have and what kind of work you prefer. Are you a React Dev? Are you a HTML/CSS expert? Do you have any design and UX background? Do you like to write documentation and examples?

Those are only guiding questions, you don't need to responde exactly then, but i would be very handful if we could have those informations. Any thoughts?

**Comment by reedhop24** [comment]
@tiagostutz, 

Professionally I work with HTML, CSS and React. I am highly proficient with all three and would love to be able to build/edit any components you need worked on!

Thanks so much!

**Comment by tiagostutz** [comment]
Awesome.! That’s really great news.

I’m thinking that maybe you could share some ideas on [#30](https://github.com/bancodobrasil/stop-analyzing-embed/issues/30) while I prepare your issue to start. It would be another valuable contribution you could give and at the same time get to know a bit more about the project.

What do you think? Sounds good?

**Comment by reedhop24** [comment]
Was the final decision to create a mix n match between styled-components and theming? I am a little confused on how a theme would work because as @bearcub3 points out, we don't create the styles based on classes. Since I am currently a little unsure how to implement a theme maybe I can get my feet wet with this first issue then revisit a little later. 

Thanks,

**Comment by tiagostutz** [comment]
Hi @reedhop24 ! Sorry for the late respose. Though week here... but everthing is just fine now.

The final decision was not to go with styled-components because it restricts the contribution of devs that are not React used ones but are great at CSS and design systems.
I'll get some references on how to build themes with CSS and will paste in #30 for us to discuss.

**Comment by reedhop24** [comment]
Hello @tiagostutz 

No problem at all! Sounds good, I will look for that discussion. In the meantime, are there any other components that need worked on/built?

Thanks,

**Comment by tiagostutz** [comment]
Hi there @reedhop24 ! 🧑‍🏭 

I just created the issue #34 for you. What do you say? If you want to get that, please comment on the issue and I'll assign it to you immediately!
