### ISSUE TITLE
I would like to contribute!

### ISSUE THREAD

**Issue by finhaa** [bancodobrasil/stop-analyzing-embed#33]
Hey!

I would like to contribute to this project. I would be delighted to contribute to this project, although i don't have much experience. I can work with HTML, CSS and JavaScript (already worked with React Native but I don't know much about React).

**Comment by tiagostutz** [comment]
Hey @finhaa !! Nice to have you on board!
I'm going to open a issue for you, but meanwhile, feel free to check other issues and if you have some thoughs to share on them, be yourself at home.

I'll come back here with your issue. 
Cheers!

**Comment by tiagostutz** [comment]
Hey @finhaa what about finishing [this](https://github.com/bancodobrasil/stop-analyzing-embed/pull/14) @bearcub3 PR #14 , by implementing the reviews and solving the conflicts so it can be merged?

If you could take that, I will assign the issue #13 to you and you can share your doubts in that issue and we will help you with this. As you have noticed, you will clone and commit directly to @bearcub3 repo. If you have any struggle with that, please comment in the issue and we will come to help you.

**Comment by finhaa** [comment]
Yeah, I accept this. I don't know much about unit tests but I believe I can contribute if I have help!

**Comment by tiagostutz** [comment]
Nice! Comment on the issue #13 please so I can assign that to you, Ok?
