### ISSUE TITLE
Implement ChoiceBoardModel with Hook

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#34]
Using Hooks, implement the ChoiceBoard component Model (to know what a model is, check how the TimerComponent was implemented).

This Model (Hook) will have:
1.  the initial 2 choice options
1. a list of already chosen itens
1. a variable to register the progress (decimal)
1. a method hat will be invoked when the card is clicked (chosen) and that will add the selected item to the list of chosen itens and will replace the 2 itens for new ones.
1. an array that will have the filtered itens when the choosing process reaches the end. This array will be returned by the backend.
1. other messaging/loading helper properties

It is not necessary to deal with the `fetch` and external calls because they are on the way and we will open another issue for that in near future.
 
Implement tests for the `useChoiceBoardModel`(Hook) to check how it behaves in different scenarios. For example: 
1. `it('should have the progress variable at 0% in the beginning of choosing process and at 100% in the end')`
1. `it('should have the 2 options always changing after a choice is made')`
1. `it('should have an array of filtered itens after choice process is done')`: after some sequential choices , the process must reaches an end with a list of filtered itens retrieved and presented.

Implement tests for the `ChoiceBoard` to check how it behaves in different scenarios. For examploe
1. `it('should render only 2 new cards every time a choice is made')`: check for changes in the card image URL or card title or card text.
1. `it('should render a message waning that there are currently no card options in english and portugueses')`
   - english message: "Sorry, there ar no available options at the moment"
   - portuguese message: "Desculpe, não há opções no momento"

1. `it('shoud render a list of returned itens after the last choice is made')`: after the choosing process, render a list of itens retrieved as a result of this proccess

**Comment by reedhop24** [comment]
Hi Tiago, 

I would love to be assigned to this issue. 

Thanks,

**Comment by tiagostutz** [comment]
Sweet! it's yours.! 🚀

**Comment by reedhop24** [comment]
Hello Tiago! 

While I was looking into implementing the ChoiceBoardModel I had a few questions:

-  Would I be correct in assuming that the URL is what needs to be stored for each selected choice?

- Will the ChoiceBoardModel make a call to a back end in order to receive the URL's for the new selections after a user is done with the current selections?

- If the above is correct then would it also be true that since the functionality on the back end is not in place yet I would not really be able to run many tests of the component until that back end is in place? 

Thank you so much for assigning to me, I am learning a ton!

**Comment by tiagostutz** [comment]
> Would I be correct in assuming that the URL is what needs to be stored for each selected choice?

I think we could store the id of the selected choice. So, consider that the JSON of a choice will be as follows: 
```
{
    "id": "xkokroewkoek",
    "title": "string",
    "subtitle": "string",
    "contentURL": "string",
    "tags": ["tag1", "tag2", "tag3"]
}
```

Makes sense?



> Will the ChoiceBoardModel make a call to a back end in order to receive the URL's for the new selections after a user is done with the current selections?

Yes, it will. Each selection will be a POST to the backend. The backend will then register the selection and return the next 2 choice options.

 
>  If the above is correct then would it also be true that since the functionality on the back end is not in place yet I would not really be able to run many tests of the component until that back end is in place?

Yes, correct. I think you could use mocks meanwhile. If you would like to know how the data will look like you could take a look at https://github.com/bancodobrasil/stop-analyzing-api/issues/8

**Comment by reedhop24** [comment]
Hi Tiago, 

I apologize but I just had two more questions about the implementation of the ChoiceBoardModel.

- What is the purpose of storing both initial options in the model if the back end is only concerned with the selected option?

- How many total choices will there be? I believe I need to know in order to calculate the percentage variable, or will that also be something returned by the back end?

Thank you so much

**Comment by tiagostutz** [comment]
Hi @reedhop24 !! First of all, there's nothing to apoligize. It's  so nice we are talking and collaborating here, the more we communicate and collaborate, the best the software will be! Thanks for being such an active member here 😉 

> What is the purpose of storing both initial options in the model if the back end is only concerned with the selected option?

Good question. I'm not sure yet and we will discuss it in another issue, but maybe we will let the user go back in his previous choices to start over from some point, so this we are keeping the choices history to enable the user to do so. If we decide not to have this "go back" feature, then we could remove this in future.

> How many total choices will there be? I believe I need to know in order to calculate the percentage variable, or will that also be something returned by the back end?

That's something the backend will return. BTW, thanks for bringing this because I've missed that in the return spec. Fixing it right now.

The return will be:
```
{
  completionRate: 0.3,
  choices: [{
    "id": "xkokroewkoek",
    "title": "title_choice_1",
    "subtitle": "subtitle_choice_1",
    "contentURL": "content_url_choice_1",
    "tags": ["tag1", "tag2", "tag3"]
  },
  {
    "id": "xkokr2432tgregoek",
    "title": "title_choice_2",
    "subtitle": "subtitle_choice_2",
    "contentURL": "content_url_choice_2",
    "tags": ["tag13", "tag24", "tag3"]
  }]
}
```

If you have any questions, comments or suggestions, I'd love to hear them...

**Comment by tiagostutz** [comment]
@reedhop24 I'm sorry, just checked that my previous message was with the JSON incomplete. I've just fixed that. Take a look please. 🧑‍💻
