### ISSUE TITLE
I would like contribute

### ISSUE THREAD

**Issue by GusFiuza** [bancodobrasil/stop-analyzing-embed#35]
Hi,

I'm just started in Open Source world and I would like contribute for this project.

I have some knowledge about HTML, CSS and JavaScript.

How can I help you?

**Comment by tiagostutz** [comment]
Hi @GusFiuza !! Welcome on board.!

Nice, I'm working on an issue for you right now. Meanwhile, let me ask you something: do you have any experience with creating CSS theme structure? If you have, you could share some thoughts at https://github.com/bancodobrasil/stop-analyzing-embed/issues/30. If you don't have but would like to contribute making a quick research about that and sharing some useful references and tips found that would be really helpful too!

**Comment by tiagostutz** [comment]
@GusFiuza would you like to contribute with https://github.com/bancodobrasil/stop-analyzing-embed/issues/36 ?

**Comment by vashugupta** [comment]
@tiagostutz for the very first time i want to contribute in any open source ongoing projects on web development but i don't no how to contribute...........!!!can you help me?

**Comment by tiagostutz** [comment]
Hi there, @vashugupta !! Welcome to stop-analyzing..! 

I'm pretty sure you will find your first steps here on how to start contributing and your work will be of great value to the project. Thanks for that.!

Could you provide me some information of what technologies are you used to work on, preferences and other information you think would be useful for me to create an issue for you?

Meanwhile, are you interested in taking one of the designs pointed by @giteshk11 in #36 to implement? If so, place a comment there and let's get the party started! 🎈

**Comment by tiagostutz** [comment]
Hi @GusFiuza and @vashugupta the issue #30 is open for assignment. Are one of you guys interested in taking that? If so, just comment on the issue and I'll assign it to you right away!

**Comment by tiagostutz** [comment]
Hi @GusFiuza and @vashugupta I just assigned the #30 to another contributor that has arrived. 
Today I'm going to open another issue for another contributor that has arrived, but as you guys arrived first I would like to know if you are still interested in one issue here or if I should open the issue for her...

**Comment by GusFiuza** [comment]
Hi @tiagostutz. Sorry! I had busy week but I still interested in one issue here. Sorry again.

**Comment by tiagostutz** [comment]
Not a problem, @GusFiuza !!

BTW, do you want to take the #51 ?

**Comment by GusFiuza** [comment]
Yes @tiagostutz. You can assign #51 for me.

**Comment by tiagostutz** [comment]
@GusFiuza there's this issue #31 that maybe you could help @eduardomrodrigues 
What do you think?

**Comment by GusFiuza** [comment]
@tiagostutz I read #31 and I think this will too hard for me. If possible, I prefer start with something more easy. I know a little bit about HTML/CSS/JavaScript, so something like #51 could be better for me.

**Comment by tiagostutz** [comment]
Sure @GusFiuza !
I'm working on an more frontend issue for you and will link it here as soon as it is ready. 👍🏻

**Comment by tiagostutz** [comment]
Hi there 👋🏻 I just created the issue #56. 
Want to tackle that? If so, just comment there and I'll assign that to you.

**Comment by GusFiuza** [comment]
Ok @tiagostutz. I saw that #56 already assigned to davidgoldcode

**Comment by Bob160** [comment]
Hi @tiagostutz 

Would like to contribute to this project too. Have some knowledge of HTML, CSS and JavaScript.

Thanks

**Comment by tiagostutz** [comment]
Hi @Bob160 ! 👋🏻 
First of all, thanks for reaching out and offering help. We are so glad to have you here.!
I just opened the issue #57 that I think you could tackle. If you want to take that, please take a quick look at the [contributing guidelines](https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/CONTRIBUTING.md) and comment in the issue so I can assign that to you.! 

Sounds good?

**Comment by tiagostutz** [comment]
> Ok @tiagostutz. I saw that #56 already assigned to davidgoldcode

Friday is a very bottling day, but don't give up we will get an issue for you! As soon as I write it I'll link it here.

**Comment by GusFiuza** [comment]
Take it easy @tiagostutz, I won't give up!

**Comment by eduardomrodrigues** [comment]
@GusFiuza, welcome to the team! If wanna any help, let me know!

**Comment by GusFiuza** [comment]
Good morning @eduardomrodrigues. I'm waiting for a issue. Something about html/css/javascript could be good.

**Comment by giteshk11** [comment]
Hi @GusFiuza,
I just created the issue #64. If you want to work on this issue I'll assign it to you

**Comment by GusFiuza** [comment]
Ok! I'll try #64. Assign it for me. Thanks!

**Comment by giteshk11** [comment]
Please self-assign, I'm not able to assign you.

**Comment by tiagostutz** [comment]
Hi @GusFiuza ! Please comment on the #64 so we can assign that to you.

@giteshk11 @divyaYK I just changed your role to **admin** in this project. 🚀 
Thanks for believing this project and giving your precious time, talent and energy to it. I hope you are enjoying this experience as much as I am.

Cheers!

**Comment by GusFiuza** [comment]
@tiagostutz, #64 commented.

**Comment by otatadeabigail** [comment]
Hi, 
This is my first time trying to contribute in open source, not quite sure how to go about it. I know HTML, CSS and very little knowledge in JavaScript. I'd like a project I can contribute to

**Comment by tiagostutz** [comment]
Hi @otatadeabigail ! 👋🏻 

Thanks for your interest in contributing. I'll review the current opened issues and will point one of them to you or will create another one that is focused on HTML and CSS and will comment here for you to grab, ok?
