### ISSUE TITLE
Create theme configuration using tailwindcss

### ISSUE THREAD

**Issue by giteshk11** [bancodobrasil/stop-analyzing-embed#36]
Create a theming structure for the application implementing [tailwindcss](https://tailwindcss.com/)

- [x] Discuss the look and feel for the theme.

**Comment by giteshk11** [comment]
@tiagostutz i'm not able to tag that guy,could you tag him and lets tag others too,who you think and help or bring more to the table for discussion.

**Comment by giteshk11** [comment]
Below are some design ideas.

- [https://dribbble.com/shots/3271222-sweet-animals](https://dribbble.com/shots/3271222-sweet-animals)
- [https://dribbble.com/shots/3579240-Sociology-Life-Life-is-always-so-good-2](https://dribbble.com/shots/3579240-Sociology-Life-Life-is-always-so-good-2)

Comment down below if you have more ideas.

**Comment by tiagostutz** [comment]
@JapneetSingh5 @eduardomrodrigues  take a look at those amazing references..!

**Comment by giteshk11** [comment]
@tiagostutz have you thought of the color schemes or do you have a color palette in mind?

**Comment by tiagostutz** [comment]
I don't have a particular color schema... that's something the theme will handle, right?

Of course, we will have to have a default color palette. Any suggestion?
There are some nice color palette generators out there. The ones I have used:
- https://coolors.co/
- https://colorhunt.co/
- http://colormind.io/
- https://www.colourlovers.com/

I think they will be useful, but first we mus decide how many colors the theme will have. Any thoughts?

**Comment by giteshk11** [comment]
> I think they will be useful but first, we must decide how many colors the theme will have. Any thoughts?

- PrimaryColor
- SecondaryColor
- AccentColor
- TextIcons
- PrimaryText
- SecondaryText
- DividerColor

**Comment by giteshk11** [comment]
![k5EYQYBqS2](https://user-images.githubusercontent.com/17675390/88010534-b8f3a500-cb32-11ea-89c2-8f03be3f4134.png)
![QI6t8r69Tc](https://user-images.githubusercontent.com/17675390/88010535-babd6880-cb32-11ea-80a7-3ba22a518f18.png)

Sample color palette. @tiagostutz

**Comment by tiagostutz** [comment]
Nice! 

Have you check how many semantic colors variables are there in Tailwind? Is it the same of Bootstrap (primary, secondary, info, danger....) or different (less or more) ?

**Comment by giteshk11** [comment]
I don't think tailwind doesn't have that out of the box. We have to add our own i guess.

**Comment by giteshk11** [comment]
@tiagostutz I'm not able to push the changes I'm getting this error 

> [error] No files matching the pattern were found: "'src/**/*.{ts,tsx,scss,css,json}'".

**Comment by tiagostutz** [comment]
> @tiagostutz I'm not able to push the changes I'm getting this error
> 
> > [error] No files matching the pattern were found: "'src/**/*.{ts,tsx,scss,css,json}'".
I had this error once but unfortunately I don't remember how I fixed that... but I remember I have fixed and pushed the changes. Is your branch up to date with the master?

Hey @eduardomrodrigues . Could you help us with this issue? Maybe you are more familiar with this kind of issue regarding to commit/push validator...

**Comment by eduardomrodrigues** [comment]
> > @tiagostutz I'm not able to push the changes I'm getting this error
> > > [error] No files matching the pattern were found: "'src/**/*.{ts,tsx,scss,css,json}'".
> 
> I had this error once but unfortunately I don't remember how I fixed that... but I remember I have fixed and pushed the changes. Is your branch up to date with the master?
> 
> Hey @eduardomrodrigues . Could you help us with this issue? Maybe you are more familiar with this kind of issue regarding to commit/push validator...

Of course! @giteshk11, this error happens when you push your changes? Can you paste all logs here? 
Thank you!

**Comment by giteshk11** [comment]
> prettier --write 'src/**/*.{ts,tsx,scss,css,json}'
>[error] No files matching the pattern were found: "'src/**/*.{ts,tsx,scss,css,json}'".
>npm ERR! code ELIFECYCLE
>npm ERR! errno 2
>npm ERR! stop-analyzing-embed@0.2.0 format: `prettier --write 'src/**/*.{ts,tsx,scss,css,json}'`
>npm ERR! Exit status 2
>npm ERR!
>npm ERR! Failed at the stop-analyzing-embed@0.2.0 format script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by giteshk11** [comment]
> > [error] No files matching the pattern were found: "'src/**/*.{ts,tsx,scss,css,json}'".

I solved this issue by removing the quotes from `prettier --write 'src/**/*.{ts,tsx,scss,css,json}'`
