### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by divyaYK** [bancodobrasil/stop-analyzing-embed#39]
Hi, I'm Divya!

I'm a beginner web developer focusing on MERN and MEAN stacks.
I'm new to Open Source development and would like to get started. 

Hoping that I could help with this project, 
Thank you.

**Comment by giteshk11** [comment]
@tiagostutz I told her about this awesome project and she wants to learn and contribute 😄

**Comment by tiagostutz** [comment]
Hi there @divyaYK, I hope you are doing well !  👋🏻 
First of all, I just loved your status!! 🍕 😆 

Welcome to stop analyzing.! It is really nice to have you on board. I'm pretty sure we will learn a lot together and build a beautiful tool that will be useful for lots of people and projects out there.

I'm going to open an issue for you asap and will link it here.

@giteshk11, I can't thank you enough for your engagement and leadership in this project. And bringing other devs like @divyaYK here is definetely something really special for the whole objective o stop-analyzing and [Poppins](https://github.com/bancodobrasil/poppins/) 🏆 ❤️ 


/please-review-my-english

PS - this **/please-review-my-english** "command" is something new we are testing which consists in asking volunteers to review your message and give suggestions on how to improve it. The idea is to make open source a great opportunity to learn english as well. The volunteer will review only the "tagged" message and not the entire thread.

**Comment by divyaYK** [comment]
Hey @tiagostutz!

Thanks for having me! 😄 
Can't wait to get started 🎉

**Comment by MarcioMad** [comment]
Hi,

@tiagostutz, your writing looks pretty solid, it'd take some good native speakers to find flaws in it.
Btw, why is please-review-my-english a "command" instead of being a proper tag?
I'm still learning the environment mechanics.

Cheers

**Comment by tiagostutz** [comment]
> Hi,
> 
> @tiagostutz, your writing looks pretty solid, it'd take some good native speakers to find flaws in it.
> Btw, why is please-review-my-english a "command" instead of being a proper tag?
> I'm still learning the environment mechanics.
> 
> Cheers

Hi! First of all, thanks for reviewing my english, @MarcioMad .!
This is a command because this review is supposed to be done just in the comments that people wish to be reviewed and not on all of the comments in the issue. If we put a tag on the issue, how would you know which comment to review? 

If you have any suggestion of a different approach, I'm open for it.

**Comment by tiagostutz** [comment]
Hey @divyaYK ! How are you doing?

What about the issue #30 ? Would you be interested in taking that? If so, please send a comment there and we will assign it to you right away.

PS - I'm eating now! 😆
