### ISSUE TITLE
I want to contribute!

### ISSUE THREAD

**Issue by ishagupta1548** [bancodobrasil/stop-analyzing-embed#40]
Hello, my name is Isha Gupta. 
I am full stack developer and follow MERN stack. I have experience of 6-7 months. I saw the project and I am interested in contributing which ever way I can. Kindly let me know.
Thank you.

**Comment by tiagostutz** [comment]
Hi @ishagupta1548 ! Glad to have on board 👋🏻
I'm sure you will bring great value to this project and we will all learn together, building an useful nice tool.!

I'm reviewing the master branch today and as soon as I finish I'll open an issue for you and link it here. Meanwhile, if you have interest in the design part of the project, you could share some ideas in #41. We would love to have more contributions there.

Can't wait to have your contributions! 😃

**Comment by ishagupta1548** [comment]
Hello @tiagostutz  Sure would definitely look into the designing and provide with my views and contributions there. Also waiting for your tag also.

**Comment by tiagostutz** [comment]
Hi @ishagupta1548 !! 👋🏻 

First of all, sorry for the late response. 
I just opened #49 and would like to know if you want to grab that?

If so, please, comment on the issue and I'll assign it to you righ way!

**Comment by tiagostutz** [comment]
Howdy @ishagupta1548 ! 

I just opened the issue #52 and I thought you would be interested in taking that.
If you want so, please post a comment there and I'll assign that to you.

Cheers!

**Comment by ishagupta1548** [comment]
I am sorry I could not reply as I was having some personal issues. I am available and want to contribute. Please assign any next issue available. Thank you @tiagostutz

**Comment by tiagostutz** [comment]
Hi there @ishagupta1548 ! 
First of all, don't worry, we are not on a rush in this project and the main goal here is to learn together giving opportunitty to people contribute. I'm very glad to have you in this community and I hope you are doing great these days.

I'm totally creating and issue for you today and will link it here.

Keep it up! 💪🏻

**Comment by tiagostutz** [comment]
@ishagupta1548 I just created #55 
If you want to grab that, please comment in the issue and I'll assign that to you right away. 🚀

**Comment by dowenrei** [comment]
Hi, is there any unassigned open issues that I could contribute to?

**Comment by tiagostutz** [comment]
Hi there @dowenrei 👋🏻 !! 

Absolutely.! Altought the current issues are all already assigned, we can create and issue specially craft for you. What do you say? Would you like to take a React Hook code to work on?

Just tell me and I'll open an issue for your right away.

Welcome on board.!

**Comment by dowenrei** [comment]
> Hi there @dowenrei 👋🏻 !!
> 
> Absolutely.! Altought the current issues are all already assigned, we can create and issue specially craft for you. What do you say? Would you like to take a React Hook code to work on?
> 
> Just tell me and I'll open an issue for your right away.
> 
> Welcome on board.!

Hi @tiagostutz, I'm quite new to React and have no experience in React Hook yet, but I would like to give it a go! ;D

**Comment by tiagostutz** [comment]
Hi there @ishagupta1548 and @dowenrei are you still interested and grabbing some issues around here? If so, just let me know and I'll create ones for you.

I hope you are doing well! =)

**Comment by RidamGarg** [comment]
Hi! I am pursuing my Bachelor's degree in Software Engineering and am looking for a project to contribute to so that I can learn new things and improve my skills.

My education mainly focused on Java, C++. The other focus of my education is web applications, so I'm pretty comfortable with  CSS, HTML, and currently learning Javascript.

**Comment by tiagostutz** [comment]
Hi there @RidamGarg 👋🏻 !! Welcome to stop-analyzing.
First of all, sorry for the late response. I was closing some old pending tasks here and got stuck on that. 

Thanks for reaching by and offering help to the project. I'm sure we will craft some issues for you to take, learn and make the project even better.! 

As you you focused in Java/C++, maybe you could help the project with the API (https://github.com/bancodobrasil/stop-analyzing-api). What do you think? If you think that's a good idea, I'll create an issue for you there. Sounds good?
