### ISSUE TITLE
Brainstorming design and layout for the app

### ISSUE THREAD

**Issue by giteshk11** [bancodobrasil/stop-analyzing-embed#41]
- Discussion on how the app should look and feel
- Build themes for the app e.g. normal and dark mode

Feel free to post your ideas or designs that you might come across over the internet.

**Comment by tiagostutz** [comment]
@giteshk11 pinned from #36 👍🏻 

Below are some design ideas.

- https://dribbble.com/shots/3271222-sweet-animals
- https://dribbble.com/shots/3579240-Sociology-Life-Life-is-always-so-good-2

There are some nice color palette generators out there. The ones I have used:

- https://coolors.co/
- https://colorhunt.co/
- http://colormind.io/
- https://www.colourlovers.com/

Suggestion on color scheme: 

    PrimaryColor
    SecondaryColor
    AccentColor
    TextIcons
    PrimaryText
    SecondaryText
    DividerColor

**Comment by giteshk11** [comment]
@tiagostutz can you make a rough drawing of the layout, so that we have a better idea of how the design should look?

**Comment by tiagostutz** [comment]
So, the idea of this component is to be embeddable inside and existing site as a component of the page, a modal or something like this. The scenario that inspired this tool was brought from [La Fiancee Wedding Dresses](https://www.lafiancee.com.br) and I think we could think that this company could have an alternative page for browsing/filtering the dresses (https://www.lafiancee.com.br/vestidos-de-noiva). So, the design should be as neutral as possible and being as theme parametrized as possible. I'm thinking something like:

![Captura de Tela 2020-07-31 às 12 19 31](https://user-images.githubusercontent.com/3986989/89050101-a1819c80-d328-11ea-941a-ff5e63de1e03.jpg)

As you can see I think we are almost there in terms of layout. Now I think we have to work on the theme parameters and on the card sizing aspects.

**Comment by tiagostutz** [comment]
Currently the card is fixed with `style={{ height: '400px' }}`. 
What do you think about that? Maybe a `flex` configuration could make the cards be always with the same size without needing to have a fixed hight. 
Do you think we should have a fixed hight (some fixed hights in the theme) and the `auto` option so this `flex` configuration would handle that, should we have only fixed heights or should we have only the auto configuration?

**Comment by giteshk11** [comment]
Flex config any day but I'm not sure how we could do that, we might have to use rows to divide the whole screen vertically let's say 3 rows (header, main content, footer) then divide the main row into two columns, that will make sure that sure the rows have min desired height for the rows and cards can take the available space. what do you think?

**Comment by tiagostutz** [comment]
Right. To be fare, I just checked again and the card behavior is already as we are talking it should be. Pretty stable. We could just change `height` to `max-height` to prevent layout crashing.

Another thing we could decide here is about the `object-fit` property of the image. I think we could go with `cover` value for that so the image doesn't get strechet, disorted or something like that.  What do you think?

**Comment by giteshk11** [comment]
Sounds good to me 👍

**Comment by giteshk11** [comment]
@tiagostutz @divyaYK  how is this colour palette [https://www.happyhues.co/palettes/12](https://www.happyhues.co/palettes/12)

**Comment by tiagostutz** [comment]
Hi @giteshk11 ! Just loved the color palette and the tailwind site is really useful for this work.! Great references.!

Maybe you could create an issue named "Tailwind Help Wanted" and put there this reference and we could drive to it the tailwind subjects. You could label it as `documentation` and them every time one asks for help with Tailwind we would refer to this in the comment. What do you think?

What about creating an issue to create a theme with this color palette?

**Comment by giteshk11** [comment]
> Maybe you could create an issue named "Tailwind Help Wanted" and put there this reference and we could drive to it the tailwind subjects. You could label it as `documentation` and them every time one asks for help with Tailwind we would refer to this in the comment. What do you think?
> 
Is it better to include this in the readme file? but your idea is also good, so let me which do you think its better?

> What about creating an issue to create a theme with this color palette?
>
Yes, we can create a new issue for this and someone can take it up.

**Comment by tiagostutz** [comment]
Hi there @giteshk11 my friend!

First of all, sorry for the late response, but I'm on a project deadline that is taking all my energy and time these past week. I hope I'll be done with it by the end of this week.

> Is it better to include this in the readme file? but your idea is also good, so let me which do you think its better?

Why not do both? We can add it to README and create the issue. I'll create the issue. Can you write the README part?

> Yes, we can create a new issue for this and someone can take it up.

Nice.! @GusFiuza (#35) is looking for a html/css/js issue. Maybe you could open this issue and offer to him. What do you think?

**Comment by giteshk11** [comment]
Hi @tiagostutz, not a problem at all, we all have commitments.
> Why not do both? We can add it to README and create the issue. I'll create the issue. Can you write the README part?

Sounds good to me.

>Nice.! @GusFiuza (#35) is looking for a html/css/js issue. Maybe you could open this issue and offer to him. What do you think?

Ok, sure I can do some reviews if you want

**Comment by giteshk11** [comment]
FYI
@tiagostutz @divyaYK [https://twitter.com/adamwathan/status/1296101617079595014](https://twitter.com/adamwathan/status/1296101617079595014)

**Comment by tiagostutz** [comment]
Totally agree.!
Just ask the assigned users whether they are still working in the issue and what are their schedule for that and just change the assignment. Can you work on that?

**Comment by tiagostutz** [comment]
BTW, I think we could define some issue stale and assignment policy for the project and place it on the CONTRIBUTING guidelines. What do you think @giteshk11 and @divyaYK?

Like in https://github.com/bancodobrasil/stop-analyzing-embed/issues/51, if we already had the policy I could explain to the contributor that I was unassigning the issue from him according to policy X, Y and Z...

What do you say? Let's discuss that on an issue?

**Comment by giteshk11** [comment]
@tiagostutz sure we can discuss on that

**Comment by divyaYK** [comment]
> What do you say? Let's discuss that on an issue?

I think that's a good idea!
