### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by beatrizrezener** [bancodobrasil/stop-analyzing-embed#5]
Hello 👋

I would like to contribute to this project.
I can help creating screens, components or styling them. 
Another way could be adding a tool for static code analysis.

Looking forward to help. Thank you!

**Comment by tiagostutz** [comment]
Hi @beatrizrezener !
Thanks for your interest in contributing to this project. I'm creating an issue for you right away.

**Comment by tiagostutz** [comment]
What about this issue #6 @beatrizrezener ? Lets do it?

**Comment by giteshk11** [comment]
Hi @tiagostutz, I would also like to contribute to this project.

**Comment by beatrizrezener** [comment]
Hello @tiagostutz, I couldn't help on #6, but I'm excited that styled components have been chosen. 

I have more time this week, would it be possible to get a new issue?

**Comment by tiagostutz** [comment]
Absolutely, @beatrizrezener !

@bearcub3 would you like to open that issue about building the tests for the events of the cards?

If you don't have time to do, I can create the issue. But if you want to do so, go on.

**Comment by bearcub3** [comment]
@tiagostutz If you don't mind, yes please do so. I will take the other test issue and rework the previous one based on your comment tomorrow.  Cheers!

**Comment by tiagostutz** [comment]
Sure, @bearcub3 ! I got this. Thanks a lot! =)

@beatrizrezener I'm working on your issue today and will let you know when its ready.

**Comment by tiagostutz** [comment]
Hi there @beatrizrezener .... first of all: I'm really sorry for the delayed.... I got a bit desorganized here and couldn't open another issue for you in the expected timing. Sorry for that.

I was thinking whether you would like to help @rafamarts on #4 . I mean, I created an over-sized issue and maybe if you could give him some help we could end this over-sized issue before the code becomes too outdated to be merged. If you think that's a good option, we can discuss in #4  what's the best way for you to help with.

What do you think?

**Comment by beatrizrezener** [comment]
Hi, Thiago!
Sure! If he tells us that I can help with something, I can contribute with that.

**Comment by tiagostutz** [comment]
Hi @beatrizrezener ! ☀️ 

What do you think about offering a helping hand to finish @bearcub3 work in #13 by the PR #14 ?

**Comment by beatrizrezener** [comment]
Hello, @tiagostutz! Unfortunately I will need to stay a week away, starting tomorrow. If when i return the issue is still open, I will be happy to collaborate!

**Comment by tiagostutz** [comment]
That’s ok! Thanks for your valuables contributions here.!

When you come back, wave your hand and will see if this or other issue needs help. ❤️

Best regards.! 🙏🏻
