### ISSUE TITLE
Reaplce styled-components by pure HTML tags

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#51]
Currently we have some components using `styled-components`. Replace those by "vanilla" html tags.
Don't need to bring the style, we will tackle the style thing on another issue.

**Comment by tiagostutz** [comment]
Hi there, @stokesy94 !! 👋🏻 

Sure, just assigned that to you.! Nice to have you on board. 😃

**Comment by stokesy94** [comment]
Hi Tiago,
I am still working on this thanks!
Matt


Sent from Yahoo Mail for iPhone


On Wednesday, August 12, 2020, 13:43, Tiago de Oliveira Stutz <notifications@github.com> wrote:




Hi @stokesy94 ! I hope you are doing well..!

I'd like to know whether you are working on this issue or if we could assign it to another contributor. If you are working on this, just let me know. If not, we could assign it to another contributor and create another one for you as soon as you want to.

What do you say?

**Comment by tiagostutz** [comment]
Hi there @stokesy94 !
This issue is reaching 30 days kinda stale and I checked that you still haven't forked the repo. I'm sorry but I have to unassign it from you because there are people looking for simple issues to contribute here and we have to keep the project pace.

If you want, I will gladly create another issue for you. ☕ 
Thanks!

**Comment by Bob160** [comment]
@tiagostutz, can I take this up?

**Comment by tiagostutz** [comment]
Hey @Bob160 ! How are you doing?
Sure, go ahead. Just assigned to you.! Nice!

🚀

**Comment by Bob160** [comment]
> Hey @Bob160 ! How are you doing?
> Sure, go ahead. Just assigned to you.! Nice!
> 
> 🚀 
> 

Hi @tiagostutz . I'm doing very well, thank you! How are you doing? Waited for you to create the new issue for me as you said but decided to choose one on my own.

Let's get to work, shall we?

**Comment by tiagostutz** [comment]
I'm doing great, thanks!

Nice move.! I've been on a rush on last weeks, thats why I couldn't create the issue... but now your are good to go! 
Please let me know whether you need any assistance.

**Comment by Bob160** [comment]
Hi @tiagostutz, can you please throw more light on what this project entails?

Thanks

**Comment by Bob160** [comment]
Hi @tiagostutz hope all is well with you?

Still waiting for your response so we can get this issue sorted. 

Hope to hear back from you soon.

Cheers

**Comment by tiagostutz** [comment]
Hi there @Bob160 ! I hope you are doing well.!
Sorry for the delay... so, this project is about creating a tool that offers a less "frictional" choosing experience for scenarios in which the user may have lots of options. As you know, choosing between lots of options requires a heavy cognitive load and can be frustrating, sometimes. This tool will offer for websites - such as e-commerces - and alternative for that.
The background brief of this project can be found here: https://github.com/bancodobrasil/stop-analyzing/issues/2

If you have any further doubts, please let me know.!

**Comment by priyanshu0405** [comment]
hey @tiagostutz, I am doing well. How are you? Yes I can take this issue, can you please explain it to me. Also, is there some place I can contact you email or something. Thanks!!

**Comment by tiagostutz** [comment]
I'm doing great, thanks!
Just assigned this issue you to you.

You can reach me at Telegram or Twitter. My user is @tiagostutz.

**Comment by OluyemisiA** [comment]
I would like to contribute to #51. How do I get started

**Comment by tiagostutz** [comment]
Hi @OluyemisiA ! 
You can put the project to run. Have you already followed the README instructions to try to put it to run?

**Comment by OluyemisiA** [comment]
@tiagostutz Yes, I followed the instructions and the project is running already

**Comment by tiagostutz** [comment]
Ok. Now, you can perform the required adjustments and submit the PR. Need any assistance on that or you are good to go?

**Comment by OluyemisiA** [comment]
I want to know if the replacement is a specific file or all the files?

**Comment by stokesy94** [comment]
Hi all,
Please can I be removed from this email chain?
Kind Regards,
Matt


Sent from Yahoo Mail for iPhone


On Saturday, October 3, 2020, 16:24, OluyemisiA <notifications@github.com> wrote:




I want to know if the replacement is a specific file or all the files?

**Comment by tiagostutz** [comment]
Hi @stokesy94 I think I'm not able to do so as it is a preference configured by you. In the e-mail you receive there's a text at the end with a link to **unsubscribe**. The text is: "Reply to this email directly, view it on GitHub, or **unsubscribe.**"

**Comment by tiagostutz** [comment]
@OluyemisiA all files, please. And also remove the imports and the package.json dependency.

**Comment by poleselfg** [comment]
i can take this if you want! @tiagostutz

**Comment by tiagostutz** [comment]
Hi there @poleselfg !! Welcome to stop-analyzing.! Thanks for offering help.

I have just assigned it to you. If you still can tackle this issue, please go ahead.
