### ISSUE TITLE
Remove all warnings from the linter

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#52]
Currently there are those warnings produced by the linter:

```
Compiled with warnings.

./src/routes/useChoiceBoardModel.ts
  Line 15:22:  'setAllOptions' is assigned a value but never used  @typescript-eslint/no-unused-vars

./src/routes/ChoiceBoard.tsx
  Line 21:11:  'selectedItems' is assigned a value but never used  @typescript-eslint/no-unused-vars

./src/components/ChoiceCard.tsx
  Line 82:9:    img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 104:11:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

```

The job is to fix them. If you need to remove things, that's ok.

**Comment by JoseChavez98** [comment]
Hi! I'll love to collaborate on the issue. Can you assign me?

**Comment by tiagostutz** [comment]
Hi 👋🏻  @JoseChavez98 ! 
Sure, I'm assigning this issue to you right now.

Thanks for helping this project. If you have any doubt or question, please feel free to comment here.

**Comment by JoseChavez98** [comment]
Thanks, @tiagostutz. Is there any guideline on how to collaborate in this project, or how does the workflow must be?

**Comment by tiagostutz** [comment]
You can check the https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/CONTRIBUTING.md file for some instructions, but if you have any question, feel free to ask here and if there is something to enhance in the CONTRIBUTING.md feel free to open an issue pointing that out.

**Comment by tiagostutz** [comment]
Hi @JoseChavez98 ! How are you doing?
I'd like to know whether you are working on this issue or if we could offer it to another contributor.? 

If you don't have time to work on that now, not a problem, we can assign it to someone else and when you be available again you can ask and we will open another issue for you.

What do you say?

Thanks!

**Comment by JoseChavez98** [comment]
Hi!, sorry for being late. 
I see that the issue is already fixed. I'll proceed to unassign me.

If you have another issue that I can work on, please let me know

**Comment by tiagostutz** [comment]
Hi @JoseChavez98 ! Not a problem, at all.!

Sure, I'll create another issue and assign it to you. Nice!
