### ISSUE TITLE
Remove the <Timercomponent /> from the ChoiceBoard component

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#53]
At the ChoiceBoard.tsx component there is a <Timercomponent /> that won't be used for now. Remove the component and the import.

**Comment by hannydevelop** [comment]
I really would love to work on this !

**Comment by tiagostutz** [comment]
Just assigned to you, @hannydevelop 
Go for it !! 🏃🏻 

Can't wait to check your PR.

**Comment by hannydevelop** [comment]
I made my first PR three hours ago!
How's it?

**Comment by hannydevelop** [comment]
> Just assigned to you, @hannydevelop
> Go for it !! 🏃🏻
> 
> Can't wait to check your PR.

Hello if my commit is OK can I get another task? I am learning React anyways

**Comment by tiagostutz** [comment]
Hi @hannydevelop ! Great PR..! 

I'm merging this right now. Meanwhile, I have just invited you as part of the team of this project. If you could accept it would be awsome. ☀️

**Comment by hannydevelop** [comment]
> Hi @hannydevelop ! Great PR..!
> 
> I'm merging this right now. Meanwhile, I have just invited you as part of the team of this project. If you could accept it would be awsome. ☀️

I would accept the request once I get 2 step authentication setup!
Thank you so much I can't wait to be part of the team.
The next task can be a React task, am learning React already
