### ISSUE TITLE
Create a parameter for the headline of ChoiceBoard

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#55]
In ChoiceBoard.tsx the headline is currently fixed as "Which one would you like to choose?".
Create a parameter in this component so the user can specify what is the headline that will be presented.

**Comment by ishagupta1548** [comment]
I want to contribute.

**Comment by tiagostutz** [comment]
Great, @ishagupta1548 ! Just assigned the issue to you.

If you struggle somehow, please comment here and someone will help asap.

I'm so glad to have your contribution to this project. I'm sure this will be a shiny PR ☀️

**Comment by ishagupta1548** [comment]
@tiagostutz  I ran the project. I saw the choiceboard.tsx. I am working on the issue.

**Comment by tiagostutz** [comment]
Hi @ishagupta1548 ! How are you doing?

Are you working on this issue? If so, just let me know. If you are not able to work right now, I can assign that to another contributor and we can create another issue for you whenever you want.

What do you say?

**Comment by Aastha2891** [comment]
Hello, @tiagostutz. Are you expecting to see a user-defined headline instead of the static "Which one would you like to choose?"

**Comment by Aarti002** [comment]
Hello everyone! i m a absolute beginner to open source  it would be really helpful if anybody help me out in this.... i mean from where should i start contributing , plz lemme know!

**Comment by tiagostutz** [comment]
Hi there @Aarti002  👋🏻 !! Welcome to stop-analyzing.
First of all, sorry for the late response. I was closing some old pending tasks here and got stuck on that.

Thanks for reaching by and offering help to the project. Would you like to tackle this issue here? If so, I can assign that to you and we can help you go through this contribution.!

**Comment by vparine** [comment]
@tiagostutz Can I work on this? Please assign this to me.

**Comment by tiagostutz** [comment]
Sure, @vparine ! Go ahead, I just assigned that to you.!

**Comment by vparine** [comment]
@tiagostutz I've raised one PR for parameterizing Headline. Request you to check once.

**Comment by Aarti002** [comment]
I'm so sorry sir for late reply just now i saw your email . I 'm ready to
take that project.Can you assign that to me now ?

**Comment by tiagostutz** [comment]
Hi @Aarti002 the issue was taken by @vparine. I have reviewd the PR at #100 and I'm waiting for his reply. If the PR "stales" I can assign it back to you. But, if you want, I can open an issue for you. What do you say?

**Comment by Aarti002** [comment]
yes sure, i would work on it. Thank you so much!!!

**Comment by vparine** [comment]
@tiagostutz Please let me know if I need to make any other changes in my PR #100

**Comment by tiagostutz** [comment]
Hey @vparine there are some changes I have requested at #100 . Have you worked on those?

Thanks!

**Comment by jvrenes** [comment]
Hi @tiagostutz,
How would you like the user to add the value of the title, using a text input or coding and modifying a constant?
Could I help on this issue?

**Comment by tiagostutz** [comment]
> Hi @tiagostutz,
> How would you like the user to add the value of the title, using a text input or coding and modifying a constant?
> Could I help on this issue?

Hi @jvrenes !! Sorry for missing your comment and taking so long to answer. My bad. 🤦🏻 

It would be a constant. In the future, this constant will be passed as a widget initialization param.

Are you still interested in working on this?

**Comment by boeing60** [comment]
Hi again ! Could I give a try to this issue ?

**Comment by tiagostutz** [comment]
Hi @boeing60 ! Sorry for the late reponse.
Sure, go ahead! I have just assigned the issue to you. =)
