### ISSUE TITLE
Add hover effect to the ChoiceCard like Pinterest

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#56]
Implement a hover effect on the card presenting the text `t("Choose")` and with the cursor `pointer`. Like this:

![Gravação-de-Tela-2020-07-31-às-11 35 10](https://user-images.githubusercontent.com/3986989/89045654-3df47080-d322-11ea-8a62-d893f31c3761.gif)

**Comment by davidgoldcode** [comment]
I'd like to contribute!

**Comment by giteshk11** [comment]
So we are using tailwind now, so try avoiding making your own classes and use tailwind classes as much as possible.
cc @tiagostutz

**Comment by tiagostutz** [comment]
Hi @davidgoldcode ! 👋🏻 
Welcome to Stop Analyzing. This is a project made by and for OSS beginners. 
So, to make your contribution, just check the contribution guidelines at https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/CONTRIBUTING.md and go for it.! This is a space for practicing and learning while building a tool I'm sure will be very useful for lots of people out there.

If you want some more background on the project, please take a look at https://github.com/bancodobrasil/stop-analyzing/issues/2

**Comment by tiagostutz** [comment]
Hi there @davidgoldcode !

Are you still working on this? Could we assign this issue to another contributor and then we create another one for you?

But, if you are working on that, that's fine. Just let me know, please.

**Comment by ydocsgnillats** [comment]
@tiagostutz I'd be happy to work on this issue if nobody else is!

**Comment by tiagostutz** [comment]
Hi @ydocsgnillats ! 👋🏻 

Welcome to Stop Analyzing. Nice to have you on board and thanks for your contribution! I'm sure we will build together such a nice tool!

I have assigned this issue to you. If you need any assistance, please let me know!

**Comment by ydocsgnillats** [comment]
Thank you @tiagostutz !
I want to make sure I'm starting off right, I plan to add an 'onCardHover()' function to the 'components/ChoiceCard.tsx' that is similar to the 'onCardClick()' function that will add the hover affect to the choice cards. Is this correct?

**Comment by tiagostutz** [comment]
You are welcome, @ydocsgnillats !! Nice to have your contribution here.

It would work, but I think we could think about making this work using `: hover` CSS property. What do you think?

@divyaYK @giteshk11 @TCashion do you think it would be possible to implement this with `:hover`? I'm not 100% sure, but really think it would be possible.

Anyway, if the CSS approach doesn't go well, please go ahead with the `onCardHover` function approach, ok?

**Comment by divyaYK** [comment]
> @divyaYK @giteshk11 @TCashion do you think it would be possible to implement this with `:hover`? I'm not 100% sure, but really think it would be possible.

Yes, hover effects can be implemented using `:hover`, I don't think using onCardHover() is necessary.
@ydocsgnillats, you can use the .css file to implement this.

**Comment by TCashion** [comment]
> @divyaYK @giteshk11 @TCashion do you think it would be possible to implement this with `:hover`? I'm not 100% sure, but really think it would be possible.

I agree with @divyaYK , `:hover` would be the most light weight way of accomplishing this.

**Comment by theSultan00** [comment]
hey there, I would like to make this my first OSS contribution, can I ? Would definitely need some guidance too

**Comment by tiagostutz** [comment]
Hi there @theSultan00  👋🏻 !! Welcome to stop-analyzing.

Thanks for reaching by and offering help to the project. We can help you in this contributing project and I'm sure you will help the project grow and have more neat features.

Do you want to take this issue here? If you think that's a good starting point, please let me know and I'll assign it to you. Don't worry, we can help you through the contributing process.

Nice to have you on board! ⛵

**Comment by theSultan00** [comment]
@tiagostutz  yes i would like to take this issue.

**Comment by tiagostutz** [comment]
Just assigned to you!
Let me know if you need any further assistance.

Thank you so much for your help.!

**Comment by theSultan00** [comment]
hello @tiagostutz so i have set up everything and got it running on my local machine, I spinned up the server and  I can see two cards on my browser I assume I'm supposed to add the text effect on those cards, so I went ahead to inspect the page I can see whats running under the hood, but when I go to the HTML page on my text editor I really can't see nothing. please can you help me out

**Comment by tiagostutz** [comment]
Ok @theSultan00. Please check the React file `ChoiceCard.tsx`. That's where you will find the code you are supposed to work on. 
Let me know if it need any further assistance!

**Comment by tiagostutz** [comment]
Hi @theSultan00, any updates on that?

**Comment by tiagostutz** [comment]
Hi @Nusart ! Welcome to stop analyzing.!
Nice to have your contribution here. Could you please take a look at https://github.com/bancodobrasil/stop-analyzing-embed/pull/104 to get some directions we have been discussing and work on this? You can fork the project and submit your PR for us to discuss and get to a solution. 

What do you say?

**Comment by Nusart** [comment]
@tiagostutz  I am not good at react. Apologies for the same. I was of the thought that this will be a stand-alone html, CSS project.

**Comment by tiagostutz** [comment]
Hi @Nusart ! Not a problem at al... if you want to give it a try, feel free to go on. But if you are not comfortable, that's fine too!

Cheers! =)

**Comment by boeing60** [comment]
Hi ! I would like to contribute to this issue if it's possible !
Have a good day.

**Comment by tiagostutz** [comment]
Hi @boeing60 ! 👋🏻 
Sure, I have just assigned that to you. Go ahead!
If you need any further assistance, please let me know.

Thanks for your help! =)

**Comment by otatadeabigail** [comment]
I'd like to contribute. How do I go about it?

**Comment by tiagostutz** [comment]
Hi there @otatadeabigail !
I have just assigned to you the issue. You can fork and go ahead with it.

Thanks a lot for your help!

**Comment by tiagostutz** [comment]
Ho there @otatadeabigail I just noticed that this issue has already been done.

Are you interested in another issue?
