### ISSUE TITLE
Use max-height instead of height and add object-fit:cover to the image element of the card

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#57]
To prevent the card from growing indefinately and cause layout crashes but giving some flexibility, change the current fix height behavior and add object-fit:cover to the element.
As we are using Tailwind utility CSS framework, please take a look at: https://tailwindcss.com/docs/object-fit/

**Comment by Bob160** [comment]
@tiagostutz This sounds good.

 I'll like to handle this with your help. 

Is that okay?

**Comment by tiagostutz** [comment]
Sure, @Bob160 ! 
I just assigned the issue to you. Go ahead and if you have any doubt or stuck in any step, please comment here and we will come to give you a hand ✋🏻 

Nice to have you on board! 

cc @giteshk11 @divyaYK

**Comment by Bob160** [comment]
@tiagostutz  @giteshk11  @divyaYK  I'm currently trying to run the project on my local machine but looks like the project doesn't use npm. 

Any help on how to run it locally so I can monitor my work?

Thanks

**Comment by tiagostutz** [comment]
@Bob160 the application is currently at the `app` folder. Check that there's a package.json there.
If it doesn't work, please let me know.

We use this pattern because there will be building logic with Docker and docker-compose.yml in the root of the project and we don't want to mess them up.

**Comment by Bob160** [comment]
@tiagostutz @giteshk11  @divyaYK  I tried running `npm start` and `npm run build` while in the `app/src` directory but had some errors as shown in the attached image. I also had to re-install `npm` in the `app` folder then retried running `npm start` and `npm run build` but still had these errors. Is there something I'm not doing right? Please, help!

I thought I'd be done with this issue and on to another one by now.
![error-on-build](https://user-images.githubusercontent.com/58000961/89103567-ad458f80-d40a-11ea-9e48-38ff930137cf.png)

**Comment by giteshk11** [comment]
@Bob160 you need to use the bash shell if you have git install you can use git bash ti run this.

**Comment by Bob160** [comment]
@tiagostutz  @giteshk11  @divyaYK  tried running it using bash shell but had this error
![error-on-build1](https://user-images.githubusercontent.com/58000961/89104413-35c72e80-d411-11ea-93f4-209d2e2c7239.png)

**Comment by giteshk11** [comment]
what command are you using?

**Comment by tiagostutz** [comment]
Looks like a problem with `bash` as it is not recognizing an environment var defined inline with the command.
@Bob160 can you try to open the Git Bash directly, not from within the VSCode? If you don't know exactly where it is installed, you could press the Windows key and write "bash", it should appear the Git Bash executable. Open it and then go to the folder and try to run from there.
Another tip, instead of executing `npm start` run `npm run dev`, which is the script used for local development.

Have you already worked with Docker? If so, I can build a Dockerfile/docker-compose specifically for development purpose with volume mapping to `app` folder and push this setup to the project to make things easier.

Let me know if the Git Bash approach worked and if it doesn't, I'll guide you through a Docker setup that I'think will work smoothly.

**Comment by Bob160** [comment]
@tiagostutz @giteshk11 @divyaYK I tried running `npm run dev` via Bash as you will see in the image below but no luck. Tried even the `npm start` and `npm run build` but to no success.

Maybe, we should try using Docker although I've never worked with Docker but I trust I'll be fine with your guidance. How about that?

![gitbash-error](https://user-images.githubusercontent.com/58000961/89133637-62fd0500-d515-11ea-8dfc-76f5556ffd06.png)

**Comment by Bob160** [comment]
@tiagostutz  running it via Bash as you suggested above worked just fine. Thanks. 

To everyone that chipped in to help, thanks too!
![gitbash-worked](https://user-images.githubusercontent.com/58000961/89133828-45c93600-d517-11ea-8496-0c22b88874b6.png)

**Comment by Bob160** [comment]
@tiagostutz @divyaYK  @giteshk11  To which class do I change the height to max-height? Is it the `img-fluid` class as shown in the image below. Am I to set the max-height to 100% as in `max-height: 100%`? 
Btw: I thought it's advisable to use one of both (width or height) rather than both (width and height)? Just my thought though, I'm new in programming.

Also, to which class do I add the `object-fit` property?


![img-fluid](https://user-images.githubusercontent.com/58000961/89134206-0e5c8880-d51b-11ea-9cf1-bfc9ff784f9f.png)

**Comment by divyaYK** [comment]
@Bob160 
- You shouldn't change a class or write a new one in .css files. We are using **[Tailwind CSS](https://tailwindcss.com/)** framework here. You can look at the docs Tiago provided in his first comment.
- You have to look for every <img /> element inside the .tsx files. Height is given as inline styles for them. You have to change it as max-height.

**Comment by Bob160** [comment]
Thanks @divyaYK . I guess the `object-fit` property is to be added to the <img /> element as an inline style too?

**Comment by giteshk11** [comment]
@Bob160 please check the tailwind documentation for object-fit class

**Comment by Bob160** [comment]
@tiagostutz  @giteshk11  and @divyaYK  Below is an image of what the content of the `<img />` would look like after changing the code. Did I get the syntax right?

![max-height](https://user-images.githubusercontent.com/58000961/89208763-e6b9fe80-d5b4-11ea-80ed-a8e2e2f84818.png)

**Comment by giteshk11** [comment]
did you check the documentation?

**Comment by tiagostutz** [comment]
Hi there, @Bob160 ! That's nice you have made some progress.! 

We are almost there, but there are two problems here for you to fix:
1. Instead of setting the `object-fit` property as an inline style, you will use what we call in modern CSS a "utility class" from Tailwind, which is our framework of choice. You will be using this: https://tailwindcss.com/docs/object-fit/. Check the example because and I'm sure you will make it work.
1. Inline styling in React is done following those guidelines here: https://reactjs.org/docs/dom-elements.html#style. You must put the properties in camelCase and some more things. As you will be using utility CSS in the `object-fit` I suggest you to create another CSS class named `h-max-400` with the `max-height: 400px` and add that. This way you won't have to deal with React specific approach. 

What do you think?

**Comment by Bob160** [comment]
@giteshk11 Yes, I did. It appears that Tailwind is some sort of CSS framework like Bootstrap.

**Comment by Bob160** [comment]
@tiagostutz thanks for the help! So, where do I create this utility class `object-fit`? Is it still in the `ChoiceCard.tsx` or `theme.css` or where exactly?

According to this link: https://tailwindcss.com/docs/object-fit/ there is a `.object-fit` class with a corresponding property and attribute but now you mentioned another `h-max-400` class which isn't mentioned in the link. Which class exactly are we using and where are we creating it?

**Comment by divyaYK** [comment]
@Bob160 

- You can add the utility class of object-fit property to the \<img\> tag. 
Not sure if the docs were clear enough for you but there's no class called .object-fit
- You can use inline styles for max-height property(CSS inline styles are slightly different in react framework) 
- Tiago meant you can write a new class called .h-max-400 in case you don't understand how CSS inline styles work in react. It's not a utility class.

**Comment by tiagostutz** [comment]
Hi there @Bob160 !
Any progress on the instructions @divyaYK gave to you? Need some more help on this? If so, tell me and I'll try to give more details to you.

Cheers!

**Comment by Bob160** [comment]
@tiagostutz  thanks for the offer. I don't seem to understand the whole class and react thing because I'm not familiar with react.

Anyway, this is my line of thought: Add the `h-max-400` to this `<img
            className="w-full img-height` that will now be `<img
            className="w-full img-height h-max-400`?

Where then does the whole `object-fit: cover` come in?

Thanks

**Comment by divyaYK** [comment]
@Bob160 

- ```<img className="w-full img-height">``` is actually old code. Could you please update your code by pulling all the new changes using 
```$ git pull origin master ```
After pulling the changes you will see inline styles specifying height's value. You can simply change it to **maxHeight**

- object-cover is the class name that exists in tailwind framework, you can simply add this name to the className attribute along with other classes.

**Comment by Bob160** [comment]
Thanks @divyaYK for the help.

@tiagostutz kindly check my PR, please. Some feedback would be appreciated.

Thanks

**Comment by tiagostutz** [comment]
> Thanks @divyaYK for the help.
> 
> @tiagostutz kindly check my PR, please. Some feedback would be appreciated.
> 
> Thanks

@Bob160 thanks for the PR!! I just commented there and @divyaYK will merge it or give some feedback. One way or another I'm creating another issue for you on monday, for sure. 

Also, I have just invited you to join the team here, if you could accept that would be awsome!!

**Comment by Bob160** [comment]
@tiagostutz Thanks for the support. I'm looking forward to the next issue on Monday, yeah!

Also, I'm truly honoured to be invited to join the team; I'll accept it and look forward to making some meaningful contributions to this project. As I'm still new to programming, I'll be relying on the outstanding support from the rest of the team.

Thanks everyone!
