### ISSUE TITLE
Implement a mock server to be used in the frontend development

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#58]
Implement a NodeJS/Express Mock server that will return mock choices so we can work on the fech thing of the frontend.

- [ ] Create a folder named "mock-server" in the root of the project
- [ ] Create a NodeJS/Express project with a `/` endpoint that returns "Greetings from stop analyzing!"
- [ ] Create an POST endpoint that receives a JSON as the request body with an array of strings, which will be the array of the selected cards. This endpoint will return a JSON array with 2 objects in the following format:
```
{
  "completeness": 0.3,
  "choices": [
    {
      "id": "5bdae89eadfea93",
      "title": "string-ttitle-1",
      "subtitle": "string-sub-1",
      "contentURL": "string-content-1",
      "attributes": [{
            "attr-name-1":"attr-value-1",
            "attr-name-2":"attr-value-2"
       }]
    },
    {
      "id": "5bdae89eeae8a99",
      "title": "string-ttitle-2",
      "subtitle": "string-sub-2",
      "contentURL": "string-content-2",
      "attributes": [{
            "attr-name-31":"attr-value-31",
            "attr-name-23":"attr-value-23"
       }]
  }]
}
```

The field completeness will be calculated by multiplying the length of the `body` JSON array by `0.2`. So, when the array has 5 elements, the completeness will be 1.

Thinking about 5 different pairs of choices, the mock server should have at least 10 different elements that will be randomized when handling the request.

**Comment by giteshk11** [comment]
@tiagostutz we can use json-server [https://github.com/typicode/json-server](https://github.com/typicode/json-server)

**Comment by hannydevelop** [comment]
> Implement a NodeJS/Express Mock server that will return mock choices so we can work on the fech thing of the frontend.
> 
> * [ ]  Create a folder named "mock-server" in the root of the project
> * [ ]  Create a NodeJS/Express project with a `/` endpoint that returns "Greetings from stop analyzing!"
> * [ ]  Create an POST endpoint that receives a JSON as the request body with an array of strings, which will be the array of the selected cards. This endpoint will return a JSON array with 2 objects in the following format:
> 
> ```
> {
>   "completeness": 0.3,
>   "choices": [
>     {
>       "id": "5bdae89eadfea93",
>       "title": "string-ttitle-1",
>       "subtitle": "string-sub-1",
>       "contentURL": "string-content-1",
>       "attributes": [{
>             "attr-name-1":"attr-value-1",
>             "attr-name-2":"attr-value-2"
>        }]
>     },
>     {
>       "id": "5bdae89eeae8a99",
>       "title": "string-ttitle-2",
>       "subtitle": "string-sub-2",
>       "contentURL": "string-content-2",
>       "attributes": [{
>             "attr-name-31":"attr-value-31",
>             "attr-name-23":"attr-value-23"
>        }]
>   }]
> }
> ```
> 
> The field completeness will be calculated by multiplying the length of the `body` JSON array by `0.2`. So, when the array has 5 elements, the completeness will be 1.
> 
> Thinking about 5 different pairs of choices, the mock server should have at least 10 different elements that will be randomized when handling the request.

I Will Starr working on this!

**Comment by tiagostutz** [comment]
> @tiagostutz we can use json-server https://github.com/typicode/json-server

Oh, I totally forgot json-server.! 
But I don't know if it will be possible to use in this scenario. Let me explain why.

The tricky thing in this mock server is that we will implement some simple business logic to emulate the progress in the choosing process request over request. It is a very simple business logic, but it need to be done for us to have the progress value consistent (increasing).

Also, we will have to pass an Array of params and have different values returned POST by POST.

But I like the idea o JSON Server if there's a way of accomplishing those requirements with them.

If you (or someone reading this issue) have ideas on how to make it work in this scenario, we definetly can change the requirements to use JSON Server.

**Comment by giteshk11** [comment]
if we are going to use some custom logic its better to build our own and there are some options in which json-sever can be used with express to create custom login.

**Comment by hannydevelop** [comment]
> * stop

I am working on this!
Will send my PR tomorrow

**Comment by hannydevelop** [comment]
> > Implement a NodeJS/Express Mock server that will return mock choices so we can work on the fech thing of the frontend.
> > 
> > * [ ]   Create a folder named "mock-server" in the root of the project
> > * [ ]   Create a NodeJS/Express project with a `/` endpoint that returns "Greetings from stop analyzing!"
> > * [ ]   Create an POST endpoint that receives a JSON as the request body with an array of strings, which will be the array of the selected cards. This endpoint will return a JSON array with 2 objects in the following format:
> > 
> > ```
> > {
> >   "completeness": 0.3,
> >   "choices": [
> >     {
> >       "id": "5bdae89eadfea93",
> >       "title": "string-ttitle-1",
> >       "subtitle": "string-sub-1",
> >       "contentURL": "string-content-1",
> >       "attributes": [{
> >             "attr-name-1":"attr-value-1",
> >             "attr-name-2":"attr-value-2"
> >        }]
> >     },
> >     {
> >       "id": "5bdae89eeae8a99",
> >       "title": "string-ttitle-2",
> >       "subtitle": "string-sub-2",
> >       "contentURL": "string-content-2",
> >       "attributes": [{
> >             "attr-name-31":"attr-value-31",
> >             "attr-name-23":"attr-value-23"
> >        }]
> >   }]
> > }
> > ```
> > 
> > 
> > The field completeness will be calculated by multiplying the length of the `body` JSON array by `0.2`. So, when the array has 5 elements, the completeness will be 1.
> > Thinking about 5 different pairs of choices, the mock server should have at least 10 different elements that will be randomized when handling the request.
> 
> I Will Starr working on this!

I am working on this, will send my PR tomorrow!

**Comment by tiagostutz** [comment]
Awesome @hannydevelop .!! 
If you need any help, I’m here. Just raise your hand! 🤚 

Thankss!!

**Comment by hannydevelop** [comment]
> Awesome @hannydevelop .!!
> If you need any help, I’m here. Just raise your hand! 🤚
> 
> Thankss!!

I am very sorry @ 

> Awesome @hannydevelop .!!
> If you need any help, I’m here. Just raise your hand! 🤚
> 
> Thankss!!

I am so sorry @tiagostutz that I haven't submitted my work yet, this is due to some power issues that would be resolved today.
Please expect my work tomorrow! Am deeply sorry once again

**Comment by tiagostutz** [comment]
Hi @hannydevelop !! 
Thanks for your message and, please, don't worry, you are at a good pace here. Communication is one of the most important things on OSS and you have been doing well on that.! 😉 

I hope those power issues are resolved as soon as possible for you and you be able to submit your work.

Just remember to reference this issue on your commits by adding `refs #58` on them so your contribution attaches to this issue.

If you need any assistance, let me know.

**Comment by hannydevelop** [comment]
Hello @tiagostutz i submitted my pull request yesterday!

**Comment by tiagostutz** [comment]
Hi @hannydevelop ! Great!

I have checked here and the PR you opened was from a branch on your fork to the master on your fork also. You should open a PR from the branch on your fork to the master of this repo here. Could you please close this PR and open another to the master of this repo? Do you need some help to do so? If you need more isntructions, just tell me here and I'll give you more details, ok?

Awesome to see your PR!

**Comment by hannydevelop** [comment]
> Hi @hannydevelop ! Great!
> 
> I have checked here and the PR you opened was from a branch on your fork to the master on your fork also. You should open a PR from the branch on your fork to the master of this repo here. Could you please close this PR and open another to the master of this repo? Do you need some help to do so? If you need more isntructions, just tell me here and I'll give you more details, ok?
> 
> Awesome to see your PR!
I will work on that immediately

**Comment by hannydevelop** [comment]
hello @tiagostutz i just implemented this now! the PR has been directed to stop-analyzing-embed:master.
![new](https://user-images.githubusercontent.com/62933980/89533437-56b1ca00-d7eb-11ea-9764-3d4ba8cf22f2.JPG)

**Comment by hannydevelop** [comment]
Hello @tiagostutz corrections are welcome on my PR i will work on them immediately!

**Comment by hannydevelop** [comment]
hello @tiagostutz i created a new PR and deleted the former! reasons why i did that is contained in a message on the PR thread.
i really had a wonderful day today, you?

**Comment by hannydevelop** [comment]
> hello @tiagostutz i created a new PR and deleted the former! reasons why i did that is contained in a message on the PR thread.
> i really had a wonderful day today, you?

Hello@tiagostutz seen the PR yet?

**Comment by hannydevelop** [comment]
> hello @tiagostutz i created a new PR and deleted the former! reasons why i did that is contained in a message on the PR thread.
> i really had a wonderful day today, you?

Hello @tiagostutz seen the PR yet?

**Comment by tiagostutz** [comment]
> hello @tiagostutz i created a new PR and deleted the former! reasons why i did that is contained in a message on the PR thread.
> i really had a wonderful day today, you?

Hello @hannydevelop !!
Good news you bring!! I'm checking your PR right now..

I had a wonderful day yesterday, yet very busy, and I'm also having one great day today, specially now that I'm checking your PR 😃
