### ISSUE TITLE
Create Like Mode card style

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#6]
Build the CSS for the "Like Mode" in Card component. The like mode is the one that the user will interact by clicking in "like" or "deslike". 

As this is the first styling issue we are opened to discuss suggestions on how to organize the CSS files. Do you have any?

**Comment by bearcub3** [comment]
@tiagostutz Hello, I'd like to contribute to your open source project. Thank you for creating this!  As a novice dev, lots of other issues labelled as first-timers-only seem intimidating or are taken by others already. haha!

**Comment by bearcub3** [comment]
@tiagostutz Hello, I'd like to contribute to your open source project. Thank you for creating this!

As you mentioned you are not going to use any CSS preprocessors, I'd like to suggest using styled-components for each component's styling and its variations and utilising Bootstrap4 for layout, components and so on at the same time.

or css module could be another option, but, if we don't plan well in the beginning, it would be more likely to have lots of repetitive css properties for similar cases or is it a natural consequence using it?

**Comment by tiagostutz** [comment]
Hi @bearcub3 ! That's so nice to have you on board. We hope we can help and learn together here and beyond!

> I'd like to contribute to your open source project.

Nice! I'll create an issue for you right away. Meanwhile, we can wait for the other contributor who requested a issue at #5 to see if she heads up here to get this issue. If she doesn't, I can assign this issue for you too.

What do you prefer: a more HTML/CSS issue, a more React issue or a more Testing issue? 

> As you mentioned you are not going to use any CSS preprocessors, I'd like to suggest using styled-components for each component's styling and its variations and utilising Bootstrap4 for layout, components and so on at the same time.

I love the styled-components idea. We are definetly going this way.

> or css module could be another option, but, if we don't plan well in the beginning, it would be more likely to have lots of repetitive css properties for similar cases or is it a natural consequence using it?

About CSS Modules, I had some struggling using it in a recent past because as the code starts to be not that "native HTML/CSS" it is harder for people that are productive in vanilla HTML/CSS to be so in the project. But, yes, there are some benefits if you do plan well in the beginning, as you said.

So, let's follow your suggestion and use styled-components and leave the css module for now.

**Comment by rafamarts** [comment]
Hello **@bearcub***,

I've liked so much of styled-components idea. I'm not the guy of CSS, but, it is not clear to me how we will use it in the practice. Are you planning to create one styled-component for each React component? I like this idea, cause it keeps the things organized.

I was wondering about the reuse of styled-components. Will we be able to reuse a styled-component, or part of it, between React components? 

It would be too much if you can brings practice samples, or even implement a little sample in the Cards component that we already have in our source code.

 Thank you so much to join us.

**Comment by bearcub3** [comment]
Thank you for welcoming me. 👍 
I can take on any HTML/CSS and React issues.
As I do not have much experience with unit testing, it would be nice to have some hands-on experience here as well. 

> I love the styled-components idea. We are definetly going this way.
😎 bring it on!!

**Comment by bearcub3** [comment]
@tiagostutz Thank you for welcoming me. 👍
I can take on any HTML/CSS and React issues.
As I do not have much experience with unit testing, it would be nice to have some hands-on experience here as well.

>I love the styled-components idea. We are definetly going this way.

😎 bring it on!!

**Comment by bearcub3** [comment]
Hello 👋  @rafamarts 

Frankly I actually haven't used styled-components. I know it is widely used for many react developers, I wanted to give it a shot! All I can say is really to spend some time to read the documentation. Once you complete merging your branch to master, I may be able to take on styling based on your work so I can show you how I would do it.
I am very much keen to conducting best practice, however, as I am still a novice, I cannot guarantee that. As this is an open source project, I hope someone can give me(us) any advice. 

As you already know React, styled-components also has the provider wrapper component and we can share the certain common styles and manipulate them passing props. If the scale of the related components gets bigger, we can probably use it later with refactor. However, at this point, I believe we can just start with the basic usage.

**Comment by tiagostutz** [comment]
@bearcub3 I've just assigned this issue to you and will create another one to beatrizrezener  (#5), ok?

I know that @rafamarts is already coding some card parts and there could be some overlapping here, but don't worry. Please create the component **standalone** and them we organize all the stuff when the all the PR's are merged. 

Sounds good?
