### ISSUE TITLE
Height of the image inside the card is not same

### ISSUE THREAD

**Issue by giteshk11** [bancodobrasil/stop-analyzing-embed#64]
The height of the image is not the same in the cards.

![qe7Jsbboo5](https://user-images.githubusercontent.com/17675390/90022247-ef56b700-dccf-11ea-9184-6afe790e321b.png)

**Comment by GusFiuza** [comment]
I would contribute #64

**Comment by tiagostutz** [comment]
Hi @GusFiuza ! 👋🏻 

I've just assigned to you the issue! Go for it!

**Comment by giteshk11** [comment]
Hi there @GusFiuza 

Are you still working on this? Could we assign this issue to another contributor and then we create another one for you?

But, if you are working on that, that's fine. Just let me know, please.

**Comment by GusFiuza** [comment]
Hi @giteshk11 

You can assign this issue to another contributor. I'm very busy nowadays. I'll ask another issue in future.

Thanks and sorry for me delay

**Comment by priyanshu0405** [comment]
@tiagostutz @giteshk11 please assign this issue to me. Thanks!!

**Comment by Ayushbajpai19** [comment]
I would like to contribute to the above issue, can you guide me through the process?
