### ISSUE TITLE
Swiping animation to dismiss the cards on button click

### ISSUE THREAD

**Issue by giteshk11** [bancodobrasil/stop-analyzing-embed#65]
The cards should have an animation when the cares are dismissed by the user.

Attached some references for animations:
- [https://animejs.com/](https://animejs.com/)
- [https://animista.net/](https://animista.net/)

If anyone has more options or references,mention in the comments below

**Comment by TCashion** [comment]
@giteshk11 @tiagostutz I'm happy to take this on, if it's still available.

**Comment by giteshk11** [comment]
Sure, I just assigned to you.

**Comment by TCashion** [comment]
@giteshk11 @tiagostutz Great! So just to clarify the use case, right now the app shows just two static cards. The animation feature I implement will be triggered when the user dismisses both options. Should I go ahead and add the dismiss button like @tiagostutz outlined in this [comment](https://github.com/bancodobrasil/stop-analyzing-embed/issues/66#issuecomment-673422936)?

**Comment by giteshk11** [comment]
@TCashion yes sure
