### ISSUE TITLE
I want to contribute! 

### ISSUE THREAD

**Issue by TCashion** [bancodobrasil/stop-analyzing-embed#67]
Hello! 

First, I'd like to say **thank you** for running this project. 

My name is Travis and I am hoping to make my first ever open-source contribution. I am a recent bootcamp grad and specialize in the MERN stack, including TypeScript.

I'd be grateful if you could guide me to an issue you're looking to solve. I noticed there are a few open already ([#64](https://github.com/bancodobrasil/stop-analyzing-embed/issues/64), [#65](https://github.com/bancodobrasil/stop-analyzing-embed/issues/65)), or I have a few ideas that might be helpful: 

1. Minor addition to the README to include instructions on how to clone the repository, plus a quick typo fix on the repo (Getting Started -> "Just follow the instructions **bellow**",  should be "**below**". 
2. Make styling updates like change the `.w-full` class to `.w-100` in the ChoiceCard.tsx and LikeCard.tsx files, as it appears `w-full` no longer exists. This results in the docker dev environment showing different styling than the node dev environment.

I'm open to any feedback or suggestions. 

Thanks again, 

Travis

**Comment by tiagostutz** [comment]
Wow @TCashion! Great tips! 🏌🏻 
That's how open source really works: tiny parts that make a great product. Thanks for pointing that.

Welcome on board of stop analyzing! I'm sure you will give valuable contributions here and learn a lot like we are all here.

I followed your suggestion and created the issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/68 for you. Just comment there and I'll assign it to you right away!

**Comment by tiagostutz** [comment]
>     2\. Make styling updates like change the `.w-full` class to `.w-100` in the ChoiceCard.tsx and LikeCard.tsx files, as it appears `w-full` no longer exists. This results in the docker dev environment showing different styling than the node dev environment.

About that... you mean in Tailwind there's no `w-full`? In [this docs](https://tailwindcss.com/docs/width) there is `w-full` but not `w-100`. I think `w-100` is a Bootstrap class, right?

**Comment by TCashion** [comment]
> > ```
> > 2\. Make styling updates like change the `.w-full` class to `.w-100` in the ChoiceCard.tsx and LikeCard.tsx files, as it appears `w-full` no longer exists. This results in the docker dev environment showing different styling than the node dev environment.
> > ```
> 
> About that... you mean in Tailwind there's no `w-full`? In [this docs](https://tailwindcss.com/docs/width) there is `w-full` but not `w-100`. I think `w-100` is a Bootstrap class, right? We migrated from Bootstrap to Tailwind.

I see what you mean... maybe I set up my Docker dev environment incorrectly, then, because when I navigate to localhost:8000, the `w-full` class exists on the card images, but there are no styling attributes associated with that class. This results in the image formatting looking incorrect (see screenshot). I'll look into this some more and come back with more info. 

<img width="1552" alt="Screen Shot 2020-08-12 at 2 38 22 PM" src="https://user-images.githubusercontent.com/58757351/90065413-7ba1b380-dca9-11ea-899b-08bb10c28815.png">

**Comment by TCashion** [comment]
@tiagostutz after diving a bit deeper, I see that the script is set up to dynamically build the main.css file in the `src/styles` directory according to line 22 on package.json: 

`"build:css": "tailwindcss build src/styles/tailwind.css -o src/styles/main.css",`

This seems to work properly when running in the node dev environment on port :3000, but I don't see the file being created in the Docker image on port :8000. 

<img width="279" alt="Screen Shot 2020-08-12 at 4 44 51 PM" src="https://user-images.githubusercontent.com/58757351/90075646-27073400-dcbb-11ea-9bf6-08472a027e26.png">
<img width="246" alt="Screen Shot 2020-08-12 at 4 45 06 PM" src="https://user-images.githubusercontent.com/58757351/90075660-2f5f6f00-dcbb-11ea-8ec0-c3048d132693.png">


Maybe this is something we can troubleshoot together?

**Comment by tiagostutz** [comment]
Sure! I'll check here the the `yarn run build` generated files because that's what the Docker build uses. The `yarn run dev` at `:3000` uses the `postcss src/styles/tailwind.css -o src/styles/main.css` CSS processor but the build uses `tailwindcss build src/styles/tailwind.css -o src/styles/main.css`. So I think that the issue is in the middle of this...

We will find out soon.!

**Comment by tiagostutz** [comment]
Hi @TCashion ! I found the problem and just fixed it. In `tailwind.config.js` it was not configured to search for typescript files `*.tsx` and `*.ts` in order to gather the classes that should be used in the generated CSS file, so it was going empty.

I just pushed this fix and now it is working. Could you please update your code and do some tests?

Thanks! 🎸

**Comment by TCashion** [comment]
@tiagostutz that worked!! Main.css file is now being created in the Docker-compose environment. 

<img width="204" alt="Screen Shot 2020-08-13 at 6 46 32 PM" src="https://user-images.githubusercontent.com/58757351/90200521-54281500-dd95-11ea-9858-d50e3641f86b.png">

**Comment by TCashion** [comment]
I'll close this issue to clear up the issue log.

**Comment by tiagostutz** [comment]
Hi there @TCashion !!

I have just invited you to join the Stop Analyzing Team in this repo. I hope you can accept that. Will be great to have you.!
🍻

**Comment by TCashion** [comment]
Thanks @tiagostutz !! It would be my pleasure!
