### ISSUE TITLE
Improvements and fixes on the README

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#68]
Minor addition to the README to include instructions on how to clone the repository, plus a quick typo fix on the repo (Getting Started -> "Just follow the instructions bellow", should be "below".

**Comment by TCashion** [comment]
@tiagostutz I would love to tackle this!

**Comment by tiagostutz** [comment]
Just take a look at the [contributing guidelines](https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/CONTRIBUTING.md) and go ahead! Just assigned to you.

BTW, if you have some contributions to add to those guidelines feel free to open the issue and bring your suggestions! 🍀
