### ISSUE TITLE
I would like to contibute

### ISSUE THREAD

**Issue by giteshk11** [bancodobrasil/stop-analyzing-embed#7]
Hi,

I would like to contribute to this project.
I can help in making designs come to life or style them.
I can help in making things dynamic using javascript.

Looking forward to contributing.
Thank you.

**Comment by tiagostutz** [comment]
Hi @giteshk11 ! That's really good to have you here.

Nice, I'm opening an issue for you right away. As you said you can help either with HTML/CSS or dynamic JS, I'm supposing that a React Component issue would be a good idea for contribution, right?

**Comment by giteshk11** [comment]
Hi @tiagostutz, I was talking about vanilla JS

**Comment by tiagostutz** [comment]
Ok. So, as we are using React, I'll think about a util in vanilla JS or a pure HTML/CSS component. Ok?

**Comment by giteshk11** [comment]
Pure HTML/CSS components are good.

**Comment by tiagostutz** [comment]
Nice! I'll create an issue for pure HTML/CSS then.. I'll come back later with your issue.

**Comment by tiagostutz** [comment]
@giteshk11 I've created the issue #8 for you. If you want to take it, please let me know commenting in the issue.

https://github.com/bancodobrasil/stop-analyzing-embed/issues/8

Ok?

**Comment by JapneetSingh5** [comment]
Hi, I have some React experience as well, would love to contribute to your project!

**Comment by tiagostutz** [comment]
Hi @JapneetSingh5 ! That's awesome.!! Welcome and let's start the trail..!

Can you take a look at this issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/9 ?

Let's discuss and decide a pattern to follow on how to separate View and Model in the React components...

**Comment by tiagostutz** [comment]
Hi @giteshk11 !
I just sent you an invite to join the team. It would be nice if you could accept it. =)

Would you like me to create another issue for you?

**Comment by giteshk11** [comment]
Hi @tiagostutz,
Thank you, I have accepted the invite.

Yes please, create another issue for me.

**Comment by tiagostutz** [comment]
@giteshk11 would you like to build a theming structure purely in CSS? I'd open a issue for you if you would like to do so.

**Comment by giteshk11** [comment]
Sure, @tiagostutz I would like do to it. Can you give me so reference links so that I could get to know a better way to do it?

**Comment by JapneetSingh5** [comment]
Hi, theming is something I also haven't worked on, can I contribute too? How do I start with it?

**Comment by tiagostutz** [comment]
Nice my friends!!

Let's start the discussion in #30 then. 🧑‍🏭

**Comment by tiagostutz** [comment]
Hi there @giteshk11  and @JapneetSingh5. Are you guys interested in grabbing the #30 ?

**Comment by giteshk11** [comment]
@tiagostutz i was looking into tailwind css the other day and it looked promising. what's your view on that?

**Comment by tiagostutz** [comment]
Hi there @giteshk11 👋 

Well, I took a look at Tailwind some time ago and it appeared to be a really good way to follow. My only concern was that the theming part of it is based on JavaScript/JSON and not CSS or SASS/LESS. I mean, if you check those JS files they are very simple and straightforward, but I this approach limits the CSS tooling and expertise we have available because this code is now on a `.js` file. That's why I think we should choose a more native CSS approach to theming. 

Now, maybe there's a way to work on theming with Tailwind using purely CSS that I've missed. Also, if you could point a way for us to build themes for Tailwind using a native CSS approach - even not following the official way - I'm so opened to it because Tailwind really caught my eyes aesthetically speaking 🤩 

What do you say?

**Comment by giteshk11** [comment]
Hi @tiagostutz ,

I just got started with tailwind and i also impressed by it. It gives more control and flexibility over the bootstrap, plus tailwind looks aesthetically good as you mentioned before.

The approach of using JavaScript for CSS makes me feel at one point it will be hard to read code if we tired to build a full theme structure, IMO and I'm not sure if we will be able to take advantages of pseudo classes that CSS gives us.

One more thing is there are lot of contributors that came on this repo and they are good with HTML,CSS but not familiar with lets say for example styled-components but if we use tailwind, one can look at the docs and start using theme quickly because they are already familiar with CSS and it would make easier for everyone. Also tailwind gives good to build our own theme you can take a look at this link 
[https://tailwindcss.com/docs/theme/#app](https://tailwindcss.com/docs/theme/#app)

These are my thoughts and we can ask others too.

**Comment by tiagostutz** [comment]
> one can look at the docs and start using theme quickly because they are already familiar with CSS and it would make easier for everyone

But, isn’t theme in Tailwind built with JavaScript? Wouldn’t it be a barrier, even with the docs? I mean, it is easier than  styled components, but still uses a JavaScript theming approach, right?


Despite of this, what do you think about opening an issue suggesting a migration from Bootstrap to Tailwind and creating a branch on your fork to start working on it? I’m convinced that we should go with Tailwind. We can discuss this theme CSS native thing in future issues.

Whats about that?

**Comment by giteshk11** [comment]
> But, isn’t theme in Tailwind built with JavaScript? Wouldn’t it be a barrier, even with the docs? I mean, it is easier than styled components, but still uses a JavaScript theming approach, right?
Oh yeah, we can build using tailwind javascript else we wont be able to take full advantage of tailwind without javascript

I'm down with using tailwind.
Lets open an issue in this repo only and start discussing about how the theme should look like and all the other specs and then you can divide the work in between new contributors. How about that?

**Comment by tiagostutz** [comment]
Sounds perfect to me.! 

Please, could you open the issue labeling it with “good first issue” and “first-timers-only” and invite the guy in #35 to take a look at that?

Glad to have such an active member like you, @giteshk11 .!!

**Comment by giteshk11** [comment]
Oh sure @tiagostutz 
Glad to be a part of this team ;)
