### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by dianalin2** [bancodobrasil/stop-analyzing-embed#70]
Hi, my name is Diana!

I'm a beginner developer, with the most experience in Flask and Django stacks. Despite not having too much familiarity with this stack, this project looked interesting, and I would love to begin open-source by contributing to it.

Thank you!

**Comment by tiagostutz** [comment]
Hi Diana.! 👋🏻
Welcome to stop analyzing.! I’m sure you will bring valuable contributions to this project even though you are not that familiar with the stack. After all, you are a dev and being so I’m sure you are eager to learn new stuff, like we all are here. BTW, learning new things is the main purpose of this project, so you reached to the right place.

I’ll create a new issue specially made for you and will link it here when it is ready to be tackled.

Nice to have you onboard.! 🥂

**Comment by tiagostutz** [comment]
@dianalin2 I hope you are doing well.!
Looks like your background is more on backend development right? If that's the case, would you be interested in tackling this issue https://github.com/bancodobrasil/stop-analyzing-api/issues/16?

**Comment by dianalin2** [comment]
Thanks, Tiago, I hope you're doing well too.

That issue sounds great! I'll be sure to reach out if I have an issue.

**Comment by tiagostutz** [comment]
Awesome!
So please post a comment there on the issue so I can assign that to you right away. If you need some help there with the environment setup and/or with the code, please feel free to comment and the issue and we will help you asap.
