### ISSUE TITLE
I want to contribute!

### ISSUE THREAD

**Issue by shettykaran21** [bancodobrasil/stop-analyzing-embed#71]
Hi! My name is Karan. I am a beginner developer. I came here from issuehub.io. I don't have experience contributing to open source projects but would love starting to do so 😁

**Comment by tiagostutz** [comment]
Hi @shettykaran21 !! 
First of all, sorry for the late response. We are so glad to have you on board!

I'll work on an issue for you asap and link it here, ok?
Do you have any restrictions about working with React or with pure HTML/CSS ?

**Comment by shettykaran21** [comment]
@tiagostutz I am not fully comfortable with React but I will try my best! 
Yeah sure, please link an issue 👍

**Comment by tiagostutz** [comment]
Not a problem at all @shettykaran21 !

I can assign to someone else and will open another issue for you and link it here, ok?

**Comment by tiagostutz** [comment]
Hey @shettykaran21 how about this issue? https://github.com/bancodobrasil/stop-analyzing-embed/issues/51

Take a look and if you want to tackle that, please comment on the issue.

**Comment by tiagostutz** [comment]
Hi @shettykaran21 ! What about the issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/55?

Want to tackle that? If so, just comment on that and we will assign that to you.!

**Comment by OluyemisiA** [comment]
Hi! My name is Adebola. I am a beginner developer. I came here from goodfirstissue.dev. I don't have experience contributing to open source projects but would love to do so 😁. I have experience with HTML, CSS, and javaScript.
Hope to hear from you soon

**Comment by sj00coder** [comment]
Hello Sir,I want to contribute.I am new to open source.Please me out.I am comfortable with react,HTML,CSS,...

**Comment by tiagostutz** [comment]
> Hi! My name is Adebola. I am a beginner developer. I came here from goodfirstissue.dev. I don't have experience contributing to open source projects but would love to do so 😁. I have experience with HTML, CSS, and javaScript.
> Hope to hear from you soon

Hi there @OluyemisiA  👋🏻 !! Welcome to stop-analyzing.
First of all, sorry for the late response. I was closing some old pending tasks here and got stuck on that.

Thanks for reaching by and offering help to the project. I'm sure we will craft some issues for you to take, learn and make the project even better.! What about the issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/51? Want to take that? If so, just comment on the issue and I'll assign it to you.!

**Comment by tiagostutz** [comment]
> Hello Sir,I want to contribute.I am new to open source.Please me out.I am comfortable with react,HTML,CSS,...

Hi there @sj00coder  👋🏻 !! Welcome to stop-analyzing. Nice to have you on board.!

Thanks for reaching by and offering help. We will craft some issues for you to take, learn and  grow the project.! 
As you are comfortable with React/HTML/CSS/JSS, what about the issue #76 ? Want to take that? If so, just comment on the issue and I'll assign it to you, ok?
