### ISSUE TITLE
I would like to contribute!

### ISSUE THREAD

**Issue by reedhop24** [bancodobrasil/stop-analyzing-embed#73]
Hello Tiago, 

I would love to tackle another issue, I would like to contribute another Component or really whatever else you need help with!

Thanks so much, 

Reed Hopkins

**Comment by tiagostutz** [comment]
Hi @reedhop24 !!
Sure thing! I'll create another issue for you... meanwhile, I've invited you to the team. You can check the invitate at https://github.com/bancodobrasil/stop-analyzing-embed/invitations. If you could accept it we'll be very honored.

As soon as I have created the issue, if you have accepted the invite I'll directly assign it to you.!

🥂

**Comment by reedhop24** [comment]
Tiago, 

I would love to join the team, is there any chance you could send over another invitation? It appears that the last one has expired.

Thanks, 

Reed Hopkins

**Comment by tiagostutz** [comment]
Sure, Reed!!

Resending the invite in 3...2..1..

**Comment by tiagostutz** [comment]
I mean, what do you think about this one https://github.com/bancodobrasil/stop-analyzing-embed/issues/76 ?
We could even break this issue in smaller ones. What do you say?

**Comment by reedhop24** [comment]
Tiago, 

I apologize for the delay, work has been hectic. I would like to tackle 76. I will get working on it, but you can probably expect to hear back from me with some questions. 

Cheers!

**Comment by tiagostutz** [comment]
@reedhop24 I've just assigned #76  to you. Feel free to ask anything about that. I'm pretty sure that me, @giteshk11, @divyaYK or any other community member will be glad to help with.!

Nice to have another issue tackeld by you, my friend!

Cheers!

**Comment by reedhop24** [comment]
Tiago,

I am so sorry I have neglected this issue, life has been hectic. When things calm down I will be sure to ask to have another issue.

Thanks so much,

Reed Hopkins
