### ISSUE TITLE
I want to contribute!

### ISSUE THREAD

**Issue by priyanshu0405** [bancodobrasil/stop-analyzing-embed#75]
Hi, my name is Priyanshu, I don't have much experience contributing, but would love to start contributing. Thanks!!

**Comment by tiagostutz** [comment]
> thanks @tiagostutz ,
> I think HTML, CSS will be fine.

Nice @priyanshu0405 ! I work on a issue for you and link it here

**Comment by tiagostutz** [comment]
> > Hello @priyanshu0405 !! 👋🏻
> > Welcome on board of Stop Analyzing! It will really good to have your contribution here.
> > This is a community made by and for beginners, so be yourself at home.!
> > So, what are you more comfortable to work with? React, Testing, HTML, CSS, Documentation..? Let me know and I'll create an issue for you right way.
> > 🥂
> 
> I also want to contribute please create one issue for me also.

Hello @sumit-kushwah 👋🏻 
Welcome on board.!

I'll create an issue for you also. Which tecnologies are you currently working with? HTML, CSS, Javascrip, NodeJS...?

**Comment by ydocsgnillats** [comment]
If there are any issues related to Javascript/React/Node i'd love to contribute!

**Comment by giteshk11** [comment]
@ydocsgnillats would you like to work on #64 ?

**Comment by giteshk11** [comment]
hi, @priyanshu0405 would you like to work on issue #64 ?

**Comment by priyanshu0405** [comment]
hello @giteshk11, yes I would like to contribute. Thanks!!

**Comment by giteshk11** [comment]
Assigned to you @priyanshu0405

**Comment by tiagostutz** [comment]
Awesome @priyanshu0405! 
Can you comment on #64 please so we can assign that to you?

@giteshk11 thanks for welcoming new users! 🥇

**Comment by Amulya-coder** [comment]
@tiagostutz Is there any issues related to html,css . I am new to the contribution but loved to start contributing.

**Comment by Amulya-coder** [comment]
@tiagostutz  Is there any issues related to html and css.I am new in the contribution to open source but loved to start contributing.

**Comment by Aastha2891** [comment]
Hello. I am new in contributing and would like to start contributing to open source. If there are any HTML and CSS related issues available, I would love to work on it.

**Comment by giteshk11** [comment]
Hello @Amulya-coder and @Aastha2891 
Thanks for taking interest in our project. Currently, there are no issues in the backlog but @tiagostutz or I will create issues soon for you.
Stay tuned!

**Comment by Amulya-coder** [comment]
@tiagostutz  is it related to html and css

**Comment by tiagostutz** [comment]
It is more related to React but is very simple. If you prefer a html/css only issue, maybe you could take a look at https://github.com/bancodobrasil/stop-analyzing-embed/issues/72 and give it a try?

What do you think?

**Comment by Amulya-coder** [comment]
@tiagostutz  I have commented on #72 could you please take a look and solve my doubt

**Comment by accordingtoherr** [comment]
Hi @tiagostutz I am experienced in React and pretty new to contributing I would love to help! - Experienced in React with SASS, Next and TypeScript

**Comment by tiagostutz** [comment]
Hi there @accordingtoherr  👋🏻 !! Welcome to stop-analyzing.

Thanks for reaching by and offering help to the project. I'm sure we will craft some issues for you to take, learn and make the project even better.!

Do you want to take a look at #72? If you think that's a good starting point, please comment on the issue and I'll assign it to you and we can help you through the contributing process.

Nice to have you on board! =)
