### ISSUE TITLE
Upgrade Tailwind to 1.7.2

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#76]
As mentioned in https://github.com/bancodobrasil/stop-analyzing-embed/issues/41#issuecomment-677708583 there's an important update on Tailwind regarding to compilation time. So it would be nice to upgrade that and check whether nothing breaks. 

A Bonus would be to create some tests that has some elements using the main Tailwind CSS utility classes used by the project to guarantee that every time we upgrade Tailwind version there won't be any severe breaks on the app. What about that?

**Comment by tiagostutz** [comment]
We don't have to build a sophisticated test that detects the Tailwind version change. We just build the test that can be manually run. So, when we have another upgrade of Tailwind we just run it to see if everything is still working.

This test should use the main Tailwind classes that we rely on and check the component states and properties to see whether it is still working as it was with the previos version. I mean, suppose we make a test that has two components with the `h-full` class. The computed height of them should be the same. So if a new Tailwind version changes the class `h-full` to `h-100` the test would break and we will quickly notice that.

If should try to keep using pure testing-library for that, but, if needed, we can build some tests Puppetter to have more controle over component rendering behavior.

Any thoughts on that?

**Comment by c-squared87** [comment]
If my other PR is up to spec on what you are looking for I would be interested in picking this issue up.

**Comment by tiagostutz** [comment]
Sure, @c-squared87 !! Just assigned the task to you.!

Also, I just invited you to the team. It would be great if you could accept this invitation.

Thanks a lot for you contributions! 🏆

**Comment by c-squared87** [comment]
Done! I'll address this issue at the top of next week.
