### ISSUE TITLE
Old TypeScript version

### ISSUE THREAD

**Issue by priyanshu0405** [bancodobrasil/stop-analyzing-embed#77]
Due to old version of TypeScript, there is problem in running the application.

![error](https://user-images.githubusercontent.com/58037946/91559553-ef081e00-e955-11ea-8212-e9d3567446ea.jpg)

**Comment by tiagostutz** [comment]
Hi @priyanshu0405 👋🏻 

Thanks for pointing that. I've just made a review on your #78 PR.
