### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by lakshay-saini-au8** [bancodobrasil/stop-analyzing-embed#79]
Hye, I am a beginner in this open-source contribution but well versed with the frontend part(HTML CSS JS REACT ). It will be great if you give me a chance to showcase my skills

**Comment by tiagostutz** [comment]
Hi @lakshay-saini-au8 !! Welcome on board of stop analyzing.! 
First of all, thanks for offering your contribution to this project. I'm sure we will build a great product here.

I'll create an issue for you asap. I'm thinking about improving our tests, do you think you could work on that? If you don't have experience with testing-library, not a problem, we can help with that.

What do you say?

**Comment by lakshay-saini-au8** [comment]
Hi @tiagostutz although I don't know much about testing, but if you can guide me on this I am up for testing

**Comment by tiagostutz** [comment]
Awesome, @lakshay-saini-au8 !

I just opened the issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/82 for you. If you would like to tackle that, please comment on the issue and I'll assign that to you.!
