### ISSUE TITLE
Create a ProgressBar component to indicate if the user is reaching the end of selection

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#8]
Create a progress bar that will be placed on top of the ChoiceBoard to indicate whether the user is reaching the end of the selection, I mean, if the selection is reaching convergence.

I created a React component at https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/app/src/components/ProgressBar.tsx with a specific CSS at https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/app/src/components/ProgressBar.css so you can focus on CSS and HTML only.

**Comment by giteshk11** [comment]
Hi @tiagostutz, I can take up this issue.

**Comment by tiagostutz** [comment]
Nice.!
I'm waiting for your PR.

Thanks.
