### ISSUE TITLE
CI platform

### ISSUE THREAD

**Issue by maximillianfx** [bancodobrasil/stop-analyzing-embed#80]
Hello people. Looking into the project and the the growing contribution, what do you think about adding some CI platform (Travis, CircleCI, Jenkins), to validate the contributions and guarantee a good code and coverage?

**Comment by tiagostutz** [comment]
Hi @maximillianfx !! Welcome to stop analyzing.! 
Thanks for your suggestion. Could you please be more specific about how the contributions validations, code coverage, etc?
I really like the idea, but to me, it looks like we are one step behind: we need more tests coded and a local code coverage tooling. Then we will add some CI platform integration. 

What do you think?

**Comment by giteshk11** [comment]
If we going with netlify we don't need ci it will automatically build

**Comment by maximillianfx** [comment]
Yeah @tiagostutz, this looks the better way, adding more tests and local code coverage tool and then add an automated tool. @giteshk11 Netlify could be a good solution, it has CI&CD, so, looks good.

**Comment by tiagostutz** [comment]
Nice, guys.

@maximillianfx maybe you could offer some help to https://github.com/bancodobrasil/stop-analyzing-embed/issues/82 ?

**Comment by maximillianfx** [comment]
Yeah, I'll check it out.
