### ISSUE TITLE
Fix current tests

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#82]
Currently the project has some tests that stopped working. Some tests can be outdated and need to be updated and others may be non-applicable anymore and hence should be removed.

After this issue is done we will start to improve the project testing coverage.

**Comment by lakshay-saini-au8** [comment]
Hye @tiagostutz here I am to take on this

**Comment by tiagostutz** [comment]
Awesome!! Just assigned to you. Let me know if you need some help on this.

Nice to have your contribution here.

**Comment by lakshay-saini-au8** [comment]
hye @tiagostutz  can you give me any tutorial or anything like that from where i can get the idea of how to start the things

**Comment by TCashion** [comment]
Hey @lakshay-saini-au8 , here are a few places to start: 

https://www.youtube.com/watch?v=D9DdY2WmM-s
https://www.valentinog.com/blog/jest/

In short, the tests run using a testing library called Jest, which integrates well with React apps. To run the test, `cd` into the `app` folder of the project, then in your terminal type `npm test`, and you'll be able to see which ones are failing.

**Comment by lakshay-saini-au8** [comment]
@TCashion thanks a lot man i will start it soon

**Comment by tiagostutz** [comment]
Great references, @TCashion.! 
The main site is https://testing-library.com/docs/react-testing-library/intro

**Comment by c-squared87** [comment]
@tiagostutz I am interested in tackling this!

**Comment by tiagostutz** [comment]
Awesome @c-squared87 !! Just assigned to you. Go for it! =)
