### ISSUE TITLE
I want to contribute!

### ISSUE THREAD

**Issue by Aastha2891** [bancodobrasil/stop-analyzing-embed#83]
Hello. I am quite new to contributing to open source but I am ready to learn and am looking for any issues which I may help with. I am comfortable with HTML/CSS. If there's anything I can contribute to, let me know. Thanks

**Comment by codecakes** [comment]
@Aastha2891 https://github.com/Xcov19/xcovfe/issues/91

**Comment by tiagostutz** [comment]
Hi @Aastha2891 ! Welcome to stop analyzing. Nice to have you on board! ⛵ 

You have the options suggested by @codecakes at Xcov19 project and we have the issue #55 here that you could tackle. If that's the case, please comment on that and I'll assign to you. 

@codecakes nice to have your suggestions here.! =)

**Comment by codecakes** [comment]
@tiagostutz thanks Tiago
