### ISSUE TITLE
I Want To Contribute!

### ISSUE THREAD

**Issue by c-squared87** [bancodobrasil/stop-analyzing-embed#84]
I have experience with React, Tailwind, and some testing with Jest. Interested in picking up tasks related to anything of that nature. Newish to open source, not new to teamwork!

**Comment by tiagostutz** [comment]
Hi @c-squared87 ! Sorry for the delay...
Welcome to stop analyzing. Nice to have you on board! ⛵

What about the #55 to warm up?

**Comment by Aarti002** [comment]
Hii , i m an absolute beginner to open source but i m very excited for my first contribution to it , i have experience in CSS/HTML and if it require some more technologies then definitely i would learn it but if there is something in which i can contribute then please let me know!

**Comment by c-squared87** [comment]
@tiagostutz Thank you for your patience, now that the holiday weekend is over I can take a shot at #55 if you want to assign that to me!

**Comment by tiagostutz** [comment]
Hi @c-squared87 .!!
Sorry for the late response. I was stuck on some pending tasks here.

Would you be interested in making a first contribution here? If so, we are needing some help on https://github.com/bancodobrasil/stop-analyzing-embed/issues/82

If so, just let me know commenting on the issue and I'll assign that to you.

**Comment by priyanshu0405** [comment]
@tiagostutz , please assign a new issue to me too. Thanks!!

**Comment by tiagostutz** [comment]
Hi there @priyanshu0405 ! Hope you are doing well!

How about taking https://github.com/bancodobrasil/stop-analyzing-embed/issues/51? If you want to tackle that, please comment on the issue and I'll assign that to you.!
