### ISSUE TITLE
I want to contribute!

### ISSUE THREAD

**Issue by brnguyenn** [bancodobrasil/stop-analyzing-embed#86]
Hi! I'm new to open source contributions, would love to contribute to this project 😄 . I have experience in React, typescript, html and css.

Accidentally created an issue on the wrong account but closed it

**Comment by tiagostutz** [comment]
Hi there @brnguyenn !! 👋🏻  First of all, sorry for the late response. 

Thanks for your interest in helping stop analyzing. Your contributions are all welcome here and I'm sure we will build together a valuable tool.

Would you be interested in working on the issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/76? If so, please comment there and I'll assign it to you. Don't worry, if you need any assistance, we got you covered.
