### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by afiorentino** [bancodobrasil/stop-analyzing-embed#87]
Hi! I recently finished my Bachelor's degree in Software Engineering and am looking for a project to contribute to so that I can learn new things and improve my skills.

My education mainly focused on OOP concepts and languages such as Python, Java, C++, but I've also taken a scripting class so I'm familiar with BASH and PERL. The other focus of my education was web applications, so I'm pretty comfortable with JavaScript, CSS, and HTML.

**Comment by tiagostutz** [comment]
Hi there @afiorentino.! Welcome to stop analyzing.!
First of all, sorry for taking so long to answer you. I was stuck on some tasks here and couldn't come back to answer the issues.

As you have some experience with Java, C++, OOP I think you could help us with one issue in the API of stop analyzing. This is the issue: https://github.com/bancodobrasil/stop-analyzing-api/issues/27
If you could tackle this issue, please comment on the issue and I'll assign that to you. Also, if you need any assistance there, just comment there and we will come to help.

Thank you so much for offering help to stop analyzing.! Welcome on board! ⛵

**Comment by afiorentino** [comment]
Hi, and thank you for welcoming me!

I believe that I should be able to tackle this issue, but I'll be sure to ask for help if I find myself lost.
