### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by RidamGarg** [bancodobrasil/stop-analyzing-embed#88]
Hi! I am pursuing my Bachelor's degree in Software Engineering and am looking for a project to contribute to so that I can learn new things and improve my skills.

My education mainly focused on Java, C++. The other focus of my education is web applications, so I'm pretty comfortable with CSS, HTML, and currently learning Javascript.

**Comment by tiagostutz** [comment]
Hi there @RidamGarg 👋🏻 !! Welcome to stop-analyzing.
First of all, sorry for the late response. I was closing some old pending tasks here and got stuck on that.

Thanks for reaching by and offering help to the project. I'm sure we will craft some issues for you to take, learn and make the project even better.!

**Comment by tiagostutz** [comment]
> Hi! I am pursuing my Bachelor's degree in Software Engineering and am looking for a project to contribute to so that I can learn new things and improve my skills.
> 
> My education mainly focused on Java, C++. The other focus of my education is web applications, so I'm pretty comfortable with CSS, HTML, and currently learning Javascript.

Hey @RidamGarg ! How about starting with a quick issue in Go in the API project? Take a look at https://github.com/bancodobrasil/stop-analyzing-api/issues/26 and if you would like to tackle that, please comment in the issue and I'll assign it to you. 🚀

**Comment by RidamGarg** [comment]
YES, I want to solve this issue.

**Comment by tiagostutz** [comment]
Awesome!! Please, comment on the issue so I can assign that to you.
