### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by kushal-khare-official** [bancodobrasil/stop-analyzing-embed#89]
Hi,
I recently learned full stack development using MERN stack. [Here](https://iert-technovation.in) is a link to the website I recently made for my college tech fest.

I want to start contributing to open source and I am also preparing for GSOC next year. Please help me out.

Thanks in advance

**Comment by tiagostutz** [comment]
Hi there @kushal-khare-official !! 👋🏻 
Welcome to stop analyzing... first of all, sorry for taking so so sooo long to answer. I was stuck on some unfinished business here.

So, we have those two issues that you could take a look at and give your contributions: #56 and #72 . What do you say?
If you want to tackle that, please comment on the issue and I'll assign it to you right away!.
