### ISSUE TITLE
Implement Hooks for ViewModels

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#9]
Hi folks! I'm working on a sample on how we are creating our components. I have an initial idea of how we can use hooks and the MVVM pattern, but would like to hear from others what are their thoughts on this.

One question, specifically would be: how do you separate your View Logic from the Model (fetch, ordering, list handlings, etc)?

**Comment by JapneetSingh5** [comment]
I have generally seen flux architecture used with React+JSX/TSX apps.
Theres a components folder and a reduc folder with the sctions and store, all of them routed via App.jsx or some other Main Component.

**Comment by JapneetSingh5** [comment]
This is one approach i think https://medium.com/swlh/how-to-structure-your-typescript-react-redux-app-877d1eba1c1e

**Comment by tiagostutz** [comment]
Nice..! 
Well, I like the Flux architecture, but particullary don't like the Redux implementation of it because I think it makes the code too verbose and with lots of indirections. I prefer the new Hooks approach introduced in React 16. It makes the code cleaner at the same time it keeps the compnent state safe. 

Have you ever worked with Hooks? If os, any thoughts on how to separated the Hooks from the components (just like the store folder in the link you provided)?

If you don't have any experience with Hooks, no problem, I can define a starting point here and assign an issue for you with all the details.

**Comment by bearcub3** [comment]
MVVM sounds great! 

When it comes to SOC, I am learning Redux at the moment. So, I’d like to talk about it.
having connected(container) components which hold the state of store would be another option. Well... whether we use Redux or not, the same rule applies.  Container components pass each state(model) as a prop to their children components. So, we can easily separate the presentational components and container components which would handle the side effects you mentioned.

**Comment by bearcub3** [comment]
> Well, I like the Flux architecture, but particullary don't like the Redux implementation of it because I think it makes the code too verbose.

I know what you mean. You have to create lots of action creators to manipulate states. But, for the large scale app, it may be something we need to compromise? 
I don’t know much about hooks yet. look forward to learn more!

**Comment by tiagostutz** [comment]
> But, for the large scale app, it may be something we need to compromise?

That's a good point and, to be fare, I've worked in large scale apps and Hooks with some helpers just worked fine for the team. I tried Redux in small and large projects and always struggled with the over-engineering, migrating it for a simpler solution. Before Hooks existed I have even implemented a (framework called Rhelena)[https://github.com/tiagostutz/rhelena] that had a cleaner approach to MVVM. With Hooks, Rhelena doesn't make sense anymore, but it helped me a lot to bring MVVM to React in a more direct way. 

That being said, I think the question we must as is: **what is the solution that better combines SOC and development agility (simplicity) to the project?** In my opinion, React Hooks provide a satisfactory SOC and is far more agile than Redux.

What do you think? Can we go with Hooks or you prefer go with Redux? Although my vote is for Hooks, if you both prefer Redux, we will use it with no problem at all.

**Comment by JapneetSingh5** [comment]
Honestly, I have struggled with over engineering in redux as well. Hooks is a very nice comcept, but I have like very little experience with it. 
Saying that, lets go with hooks, it will be a great learning opportunity.

**Comment by bearcub3** [comment]
I see. Hooks sound great! This will be another learning opportunity for me as well. 
Let's go for it!

**Comment by tiagostutz** [comment]
Great!
I'm working on a sample component that uses Hook to be used as a reference and in two issues for you to grap. As soon as they are ready I'll link them here.

Thanks again! It will be a great experience.

**Comment by tiagostutz** [comment]
@JapneetSingh5 how about this issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/12 ? If you think you can take it, give a heads up there, please.

**Comment by tiagostutz** [comment]
@bearcub3 I've create this issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/13 that mixes Hooks, Component SOC and Testing. Want to grab that? If so, please comment in there in the issue and I will assign it to you.

**Comment by bearcub3** [comment]
@tiagostutz sure, as I do not much practical react testing experience yet, it may take some time. I will take it!

**Comment by tiagostutz** [comment]
@bearcub3 that’s perfect! Don’t worry about the time, the important thing here is go keep going.

I don’t know if you have noticed on README, but this project is a [Poppins project](https://github.com/bancodobrasil/poppins) and hence the main goal here is the open source learning process/path, so there’s no rush on time boxes. We are all learning together. BTW you are going very fast... that’s been great! heheheheheheh.

Of course, we are building a real software here, but on a apprentice pace.

I have sent you an invite to join the project team as you have a good PR merged. If you could accept I can assign the #13 to you. If don’t want to accept now, that’s not a problem, just post a comment on the issue so I can assign that to you either. I mean, to assing the issue to you you either need to be part of the team or part of the issue discussion.

**Comment by bearcub3** [comment]
@tiagostutz  Yes, I already have read the README and that sounds really ideal for people like me. Thank you for taking the initiative. I have a limited development experience and want to keep the pace of CI/CD development. 😄 

I have accepted your invitation yesterday evening. I am wondering if I am a part of the team now.
