### ISSUE TITLE
I want to contribute!

### ISSUE THREAD

**Issue by kasheravaibhav14** [bancodobrasil/stop-analyzing-embed#90]
I am Vaibhav Kashera, studying at the International Institute of Information Technology, Hyderabad(IIIT-H).
My past experiences include creating an android application in a team in Flutter and Firebase, which can be viewed [here](https://play.google.com/store/apps/details?id=com.collegenet.myapp&hl=en).
I am comfortable working in C, C++, JS, Python3, Django, and Dart. I also have a fair amount of exposure to web development(bootstrap, js, Django). I would like to contribute to this repository to kick off my work in open source.

**Comment by kasheravaibhav14** [comment]
Hey, can I please get some response? It's been 9 days!

**Comment by tiagostutz** [comment]
Hi @kasheravaibhav14 ! I'm so sorry for the late response... 

As you have some experience with backend technologies, maybe you could take a look at https://github.com/bancodobrasil/stop-analyzing-api/issues/26 and check if you could contribute with that?
If so, please comment  on the issue and then I'll assign that to you. 

What do you think?

Thanks!!

**Comment by kasheravaibhav14** [comment]
Yeah sure, I'll take it!
