### ISSUE TITLE
Implement script to run mock server from `npm run`

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#93]
Add to package.json a script to bring up the `mock-server`. The command will be `npm run mock-server`.

**Comment by ashkankamyab** [comment]
Hi @tiagostutz 
Hi I would like to work on this, would you mind assign it to me please?

**Comment by tiagostutz** [comment]
Hi there @ashkankamyab.! 👋

Welcome to stop analyzing. Thanks foe your support and interest in contributing.!

I'm assigning this issue to you right now. If you need any assistance, please let me know.!

Let's do it.!

**Comment by YASH3166** [comment]
Hi I would like to work on this, would you mind assign it to me please

**Comment by shalika10** [comment]
hey is it still open ??? can you please assign it to me if its still open

**Comment by tiagostutz** [comment]
Hi there @shalika10 !! Sorry for the late answer. Are you still interested in this?
I'm assigning it to you right now!

**Comment by kazukilapislazuli** [comment]
Can I work on this?

**Comment by shalika10** [comment]
@tiagostutz  thanks i will work on this and will create a PR shortly

**Comment by shalika10** [comment]
@tiagostutz  i have raised the PR kindly check and let me know if it need some re-work or is it good to go
