### ISSUE TITLE
Implement query params on /choice of mock-server to emulate the next choice action

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#95]
Following the https://github.com/bancodobrasil/stop-analyzing-api/issues/16#issuecomment-667519483 spec, this issue is about enchancing the `db` and the `/choice` endpoint of the mocking server so it can return different values with sequentials invocations to emulate how the real API will behave so we can work on the progress visual interaction and the final interaction when the user reaches "the end of the line".

**Comment by YASH3166** [comment]
Can you hand me this project?

**Comment by phr-nk** [comment]
I can help with this issue.

**Comment by tiagostutz** [comment]
Hi @phr-nk are you still interested on that issue?
